Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLmidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLmidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLmidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/premierleague/PLmidfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name               0
Team               0
Tackles            0
Clearances         0
Interceptions      0
aerialsWon         0
Blocks             0
Mins               0
duelsWon           0
unnamed          129
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000,0.0
mean,27.046512,59.116279,16.147287,27.612403,2.341085,1468.984496,73.240310,NaN
std,22.195108,52.984613,14.091277,28.899965,2.611561,1050.951711,56.925496,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,9.000000,17.000000,4.000000,7.000000,0.000000,486.000000,24.000000,NaN
50%,22.000000,45.000000,15.000000,19.000000,2.000000,1377.000000,61.000000,NaN
75%,40.000000,83.000000,23.000000,42.000000,4.000000,2358.000000,117.000000,NaN
max,115.000000,220.000000,66.000000,148.000000,12.000000,3420.000000,216.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 2483)
dfDdef["ID"] = (dfDdef.index + 2483)
dfDatt["ID"] = (dfDatt.index + 2483)
dfDpas["ID"] = (dfDpas.index + 2483) #should end at id no 2611
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 2663
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 2698
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 2823
dfMdft.head(300) #to check final id number

              Name                    Team  App  Mins    ID
0        J. Milner  Brighton & Hove Albion    4   173  2699
1       A. Lallana             Southampton   20   377  2700
2       R. Barkley             Aston Villa   24   615  2701
3         I. Gueye                 Everton   37  3072  2702
4         Casemiro       Manchester United   38  1513  2703
..             ...                     ...  ...   ...   ...
120  S. Amo-Ameyaw             Southampton    9    26  2819
121       T. Nyoni               Liverpool    4     0  2820
122   C. Echeverri         Manchester City    1    11  2821
123   H. Armstrong                 Everton   23    47  2822
124    HHH. Howell  Brighton & Hove Albion    5    14  2823

[125 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/premierleague/PLdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/premierleague/PLforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/premierleague/PLgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/premierleague/PLmidfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,J. Evans,Manchester United,17,314,2483,0,2.0,1,0,0.1270,NaN,0.0247,8,15,5,10,0,24,214,190,12,0,0,0,Defender,NaN
1,N. Clyne,Crystal Palace,37,504,2484,0,2.0,0,0,0.0241,NaN,0.2360,12,13,3,1,0,15,203,158,31,7,0,3,Defender,NaN
2,K. Walker,Burnley,17,973,2485,0,5.0,2,0,0.1429,NaN,1.3338,17,11,3,9,2,34,731,648,55,14,2,7,Defender,NaN
3,C. Dawson,Wolverhampton,21,987,2486,0,5.0,1,0,0.4923,NaN,0.0664,15,51,9,21,1,42,558,484,85,0,0,2,Defender,NaN
4,K. Trippier,Newcastle United,31,1328,2487,3,4.0,0,0,0.1241,NaN,1.4518,38,42,12,22,2,75,1038,886,77,82,2,22,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,H. Elliott,Aston Villa,30,399,2778,2,17.0,4,1,1.7614,NaN,0.6431,5,3,1,1,4,11,269,229,24,12,1,10,Midfielder,NaN
296,M. Mudryk,Chelsea,12,158,2779,0,1.0,1,0,0.2504,NaN,0.4870,2,1,0,2,0,9,35,27,1,7,2,2,Midfielder,NaN
297,M. Wieffer,Brighton & Hove Albion,28,1045,2780,4,9.0,4,1,0.7548,NaN,1.0039,58,25,17,34,1,107,647,559,31,13,1,16,Midfielder,NaN
298,N. Madueke,Arsenal,33,2060,2781,3,80.0,32,7,9.6434,NaN,3.1497,25,10,10,11,23,106,599,501,20,63,6,34,Midfielder,NaN
299,E. Fernández,Chelsea,36,2946,2782,7,53.0,20,6,6.1270,NaN,6.2175,65,20,13,15,14,159,1778,1489,172,109,13,81,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,J. Evans,Manchester United,17,314,2483,0,2.0,1,0,0.1270,0.0,0.0247,8,15,5,10,0,24,214,190,12,0,0,0,Defender,0.0
1,N. Clyne,Crystal Palace,37,504,2484,0,2.0,0,0,0.0241,0.0,0.2360,12,13,3,1,0,15,203,158,31,7,0,3,Defender,0.0
2,K. Walker,Burnley,17,973,2485,0,5.0,2,0,0.1429,0.0,1.3338,17,11,3,9,2,34,731,648,55,14,2,7,Defender,0.0
3,C. Dawson,Wolverhampton,21,987,2486,0,5.0,1,0,0.4923,0.0,0.0664,15,51,9,21,1,42,558,484,85,0,0,2,Defender,0.0
4,K. Trippier,Newcastle United,31,1328,2487,3,4.0,0,0,0.1241,0.0,1.4518,38,42,12,22,2,75,1038,886,77,82,2,22,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,Y. Minteh,Brighton & Hove Albion,33,1854,2814,4,34.0,16,6,4.1104,0.0,5.0135,48,28,11,18,7,122,444,305,25,91,8,29,Midfielder,0.0
332,L. Miley,Newcastle United,26,324,2815,0,3.0,2,1,0.5450,0.0,0.2880,14,5,2,6,1,22,190,168,8,0,0,1,Midfielder,0.0
333,M. Golding,Leicester City,2,1,2816,0,0.0,0,0,0.0000,0.0,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
334,T. George,Everton,19,184,2817,1,3.0,1,1,0.1989,0.0,0.2602,2,1,2,0,1,5,50,41,4,3,1,6,Midfielder,0.0
335,C. Olusesi,Tottenham Hotspur,14,0,2818,0,0.0,0,0,0.0000,0.0,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,2483,Defender,J. Evans,Manchester United,17,314,0,2.0,1,0,0.1270,0.0,0.0247,8,15,5,10,0,24,214,190,12,0,0,0,0.0
1,2484,Defender,N. Clyne,Crystal Palace,37,504,0,2.0,0,0,0.0241,0.0,0.2360,12,13,3,1,0,15,203,158,31,7,0,3,0.0
2,2485,Defender,K. Walker,Burnley,17,973,0,5.0,2,0,0.1429,0.0,1.3338,17,11,3,9,2,34,731,648,55,14,2,7,0.0
3,2486,Defender,C. Dawson,Wolverhampton,21,987,0,5.0,1,0,0.4923,0.0,0.0664,15,51,9,21,1,42,558,484,85,0,0,2,0.0
4,2487,Defender,K. Trippier,Newcastle United,31,1328,3,4.0,0,0,0.1241,0.0,1.4518,38,42,12,22,2,75,1038,886,77,82,2,22,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,2814,Midfielder,Y. Minteh,Brighton & Hove Albion,33,1854,4,34.0,16,6,4.1104,0.0,5.0135,48,28,11,18,7,122,444,305,25,91,8,29,0.0
332,2815,Midfielder,L. Miley,Newcastle United,26,324,0,3.0,2,1,0.5450,0.0,0.2880,14,5,2,6,1,22,190,168,8,0,0,1,0.0
333,2816,Midfielder,M. Golding,Leicester City,2,1,0,0.0,0,0,0.0000,0.0,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0
334,2817,Midfielder,T. George,Everton,19,184,1,3.0,1,1,0.1989,0.0,0.2602,2,1,2,0,1,5,50,41,4,3,1,6,0.0
335,2818,Midfielder,C. Olusesi,Tottenham Hotspur,14,0,0,0.0,0,0,0.0000,0.0,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.0,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.00000,341.000000,341.000000,341.000000,341.00000
mean,2653.000000,26.571848,1499.137830,1.627566,19.636364,7.000000,2.260997,2.248686,0.0,1.446391,26.495601,33.504399,12.035191,19.835777,5.697947,75.354839,693.243402,584.205279,68.13783,25.727273,3.032258,14.914956,4.42522
std,98.582453,10.701497,1063.941579,2.535455,24.769817,10.246664,4.021915,3.612950,0.0,1.850188,25.581774,40.766669,12.941222,23.893686,7.573151,62.200957,580.035726,511.238829,107.24541,39.717963,4.327289,17.911591,19.11031
min,2483.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000
25%,2568.000000,20.000000,481.000000,0.000000,2.000000,0.000000,0.000000,0.124100,0.0,0.088300,5.000000,6.000000,2.000000,4.000000,0.000000,16.000000,190.000000,158.000000,10.00000,1.000000,0.000000,2.000000,0.00000
50%,2653.000000,30.000000,1533.000000,0.000000,10.000000,3.000000,1.000000,0.771100,0.0,0.688200,19.000000,19.000000,8.000000,11.000000,3.000000,64.000000,598.000000,492.000000,32.00000,7.000000,1.000000,8.000000,0.00000
75%,2738.000000,36.000000,2440.000000,2.000000,28.000000,9.000000,3.000000,2.697600,0.0,2.037900,39.000000,45.000000,19.000000,25.000000,8.000000,122.000000,1038.000000,857.000000,83.00000,30.000000,4.000000,22.000000,0.00000
max,2823.000000,38.000000,3420.000000,18.000000,130.000000,61.000000,29.000000,25.367400,0.0,9.262700,133.000000,220.000000,66.000000,148.000000,44.000000,243.000000,2922.000000,2679.000000,886.00000,202.000000,27.000000,91.000000,125.00000

We actually have expected stats covered within this league, allowing us to have further analytics for these sets of players.

Adding additional data fields

In [16]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90

#expected stats
#xg per 90
finalData["xgPer90"] = finalData["xG"] / finalData["Mins"] * 90
#npxg per 90
finalData["npxgPer90"] = finalData["npxG"] / finalData["Mins"] * 90
#xa per 90
finalData["xaPer90"] = finalData["xA"] / finalData["Mins"] * 90

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2483,Defender,J. Evans,Manchester United,17,314,0,2.0,1,0,0.1270,0.0,0.0247,8,15,5,10,0,24,214,190,12,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.573248,0.286624,6.878981,61.337580,54.458599,3.439490,0.000000,0.000000,0.000000,2.292994,4.299363,1.433121,2.866242,0.000000,0.0,0.036401,0.0,0.007080
1,2484,Defender,N. Clyne,Crystal Palace,37,504,0,2.0,0,0,0.0241,0.0,0.2360,12,13,3,1,0,15,203,158,31,7,0,3,0.0,0.000000,0.000000,0,0.000000,0.357143,0.000000,2.678571,36.250000,28.214286,5.535714,1.250000,0.000000,0.535714,2.142857,2.321429,0.535714,0.178571,0.000000,0.0,0.004304,0.0,0.042143
2,2485,Defender,K. Walker,Burnley,17,973,0,5.0,2,0,0.1429,0.0,1.3338,17,11,3,9,2,34,731,648,55,14,2,7,0.0,0.000000,0.000000,0,0.000000,0.462487,0.184995,3.144913,67.615622,59.938335,5.087359,1.294964,0.184995,0.647482,1.572456,1.017472,0.277492,0.832477,0.184995,0.0,0.013218,0.0,0.123373
3,2486,Defender,C. Dawson,Wolverhampton,21,987,0,5.0,1,0,0.4923,0.0,0.0664,15,51,9,21,1,42,558,484,85,0,0,2,0.0,0.000000,0.000000,0,0.000000,0.455927,0.091185,3.829787,50.881459,44.133739,7.750760,0.000000,0.000000,0.182371,1.367781,4.650456,0.820669,1.914894,0.091185,0.0,0.044891,0.0,0.006055
4,2487,Defender,K. Trippier,Newcastle United,31,1328,3,4.0,0,0,0.1241,0.0,1.4518,38,42,12,22,2,75,1038,886,77,82,2,22,0.0,0.000000,0.203313,3,0.203313,0.271084,0.000000,5.082831,70.346386,60.045181,5.218373,5.557229,0.135542,1.490964,2.575301,2.846386,0.813253,1.490964,0.135542,0.0,0.008410,0.0,0.098390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,2814,Midfielder,Y. Minteh,Brighton & Hove Albion,33,1854,4,34.0,16,6,4.1104,0.0,5.0135,48,28,11,18,7,122,444,305,25,91,8,29,0.0,0.291262,0.194175,10,0.485437,1.650485,0.776699,5.922330,21.553398,14.805825,1.213592,4.417476,0.388350,1.407767,2.330097,1.359223,0.533981,0.873786,0.339806,0.0,0.199534,0.0,0.243374
332,2815,Midfielder,L. Miley,Newcastle United,26,324,0,3.0,2,1,0.5450,0.0,0.2880,14,5,2,6,1,22,190,168,8,0,0,1,0.0,0.277778,0.000000,1,0.277778,0.833333,0.555556,6.111111,52.777778,46.666667,2.222222,0.000000,0.000000,0.277778,3.888889,1.388889,0.555556,1.666667,0.277778,0.0,0.151389,0.0,0.080000
333,2816,Midfielder,M. Golding,Leicester City,2,1,0,0.0,0,0,0.0000,0.0,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000
334,2817,Midfielder,T. George,Everton,19,184,1,3.0,1,1,0.1989,0.0,0.2602,2,1,2,0,1,5,50,41,4,3,1,6,0.0,0.489130,0.489130,2,0.978261,1.467391,0.489130,2.445652,24.456522,20.054348,1.956522,1.467391,0.489130,2.934783,0.978261,0.489130,0.978261,0.000000,0.489130,0.0,0.097288,0.0,0.127272
335,2818,Midfielder,C. Olusesi,Tottenham Hotspur,14,0,0,0.0,0,0,0.0000,0.0,0.0000,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Removing NaN again and fixing decimal places

In [17]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2483,Defender,J. Evans,Manchester United,17,314,0,2.0,1,0,0.13,0.0,0.02,8,15,5,10,0,24,214,190,12,0,0,0,0.0,0.00,0.00,0,0.00,0.57,0.29,6.88,61.34,54.46,3.44,0.00,0.00,0.00,2.29,4.30,1.43,2.87,0.00,0.0,0.04,0.0,0.01
1,2484,Defender,N. Clyne,Crystal Palace,37,504,0,2.0,0,0,0.02,0.0,0.24,12,13,3,1,0,15,203,158,31,7,0,3,0.0,0.00,0.00,0,0.00,0.36,0.00,2.68,36.25,28.21,5.54,1.25,0.00,0.54,2.14,2.32,0.54,0.18,0.00,0.0,0.00,0.0,0.04
2,2485,Defender,K. Walker,Burnley,17,973,0,5.0,2,0,0.14,0.0,1.33,17,11,3,9,2,34,731,648,55,14,2,7,0.0,0.00,0.00,0,0.00,0.46,0.18,3.14,67.62,59.94,5.09,1.29,0.18,0.65,1.57,1.02,0.28,0.83,0.18,0.0,0.01,0.0,0.12
3,2486,Defender,C. Dawson,Wolverhampton,21,987,0,5.0,1,0,0.49,0.0,0.07,15,51,9,21,1,42,558,484,85,0,0,2,0.0,0.00,0.00,0,0.00,0.46,0.09,3.83,50.88,44.13,7.75,0.00,0.00,0.18,1.37,4.65,0.82,1.91,0.09,0.0,0.04,0.0,0.01
4,2487,Defender,K. Trippier,Newcastle United,31,1328,3,4.0,0,0,0.12,0.0,1.45,38,42,12,22,2,75,1038,886,77,82,2,22,0.0,0.00,0.20,3,0.20,0.27,0.00,5.08,70.35,60.05,5.22,5.56,0.14,1.49,2.58,2.85,0.81,1.49,0.14,0.0,0.01,0.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,2814,Midfielder,Y. Minteh,Brighton & Hove Albion,33,1854,4,34.0,16,6,4.11,0.0,5.01,48,28,11,18,7,122,444,305,25,91,8,29,0.0,0.29,0.19,10,0.49,1.65,0.78,5.92,21.55,14.81,1.21,4.42,0.39,1.41,2.33,1.36,0.53,0.87,0.34,0.0,0.20,0.0,0.24
332,2815,Midfielder,L. Miley,Newcastle United,26,324,0,3.0,2,1,0.55,0.0,0.29,14,5,2,6,1,22,190,168,8,0,0,1,0.0,0.28,0.00,1,0.28,0.83,0.56,6.11,52.78,46.67,2.22,0.00,0.00,0.28,3.89,1.39,0.56,1.67,0.28,0.0,0.15,0.0,0.08
333,2816,Midfielder,M. Golding,Leicester City,2,1,0,0.0,0,0,0.00,0.0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00
334,2817,Midfielder,T. George,Everton,19,184,1,3.0,1,1,0.20,0.0,0.26,2,1,2,0,1,5,50,41,4,3,1,6,0.0,0.49,0.49,2,0.98,1.47,0.49,2.45,24.46,20.05,1.96,1.47,0.49,2.93,0.98,0.49,0.98,0.00,0.49,0.0,0.10,0.0,0.13
335,2818,Midfielder,C. Olusesi,Tottenham Hotspur,14,0,0,0.0,0,0,0.00,0.0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00

Adding and moving "League" column

In [18]:
#label
leagueLabel = "Premier League"

#adding label to df
finalData["League"] = leagueLabel

In [19]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
0,2483,Defender,Premier League,J. Evans,Manchester United,17,314,0,2.0,1,0,0.13,0.0,0.02,8,15,5,10,0,24,214,190,12,0,0,0,0.0,0.00,0.00,0,0.00,0.57,0.29,6.88,61.34,54.46,3.44,0.00,0.00,0.00,2.29,4.30,1.43,2.87,0.00,0.0,0.04,0.0,0.01
1,2484,Defender,Premier League,N. Clyne,Crystal Palace,37,504,0,2.0,0,0,0.02,0.0,0.24,12,13,3,1,0,15,203,158,31,7,0,3,0.0,0.00,0.00,0,0.00,0.36,0.00,2.68,36.25,28.21,5.54,1.25,0.00,0.54,2.14,2.32,0.54,0.18,0.00,0.0,0.00,0.0,0.04
2,2485,Defender,Premier League,K. Walker,Burnley,17,973,0,5.0,2,0,0.14,0.0,1.33,17,11,3,9,2,34,731,648,55,14,2,7,0.0,0.00,0.00,0,0.00,0.46,0.18,3.14,67.62,59.94,5.09,1.29,0.18,0.65,1.57,1.02,0.28,0.83,0.18,0.0,0.01,0.0,0.12
3,2486,Defender,Premier League,C. Dawson,Wolverhampton,21,987,0,5.0,1,0,0.49,0.0,0.07,15,51,9,21,1,42,558,484,85,0,0,2,0.0,0.00,0.00,0,0.00,0.46,0.09,3.83,50.88,44.13,7.75,0.00,0.00,0.18,1.37,4.65,0.82,1.91,0.09,0.0,0.04,0.0,0.01
4,2487,Defender,Premier League,K. Trippier,Newcastle United,31,1328,3,4.0,0,0,0.12,0.0,1.45,38,42,12,22,2,75,1038,886,77,82,2,22,0.0,0.00,0.20,3,0.20,0.27,0.00,5.08,70.35,60.05,5.22,5.56,0.14,1.49,2.58,2.85,0.81,1.49,0.14,0.0,0.01,0.0,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,2814,Midfielder,Premier League,Y. Minteh,Brighton & Hove Albion,33,1854,4,34.0,16,6,4.11,0.0,5.01,48,28,11,18,7,122,444,305,25,91,8,29,0.0,0.29,0.19,10,0.49,1.65,0.78,5.92,21.55,14.81,1.21,4.42,0.39,1.41,2.33,1.36,0.53,0.87,0.34,0.0,0.20,0.0,0.24
332,2815,Midfielder,Premier League,L. Miley,Newcastle United,26,324,0,3.0,2,1,0.55,0.0,0.29,14,5,2,6,1,22,190,168,8,0,0,1,0.0,0.28,0.00,1,0.28,0.83,0.56,6.11,52.78,46.67,2.22,0.00,0.00,0.28,3.89,1.39,0.56,1.67,0.28,0.0,0.15,0.0,0.08
333,2816,Midfielder,Premier League,M. Golding,Leicester City,2,1,0,0.0,0,0,0.00,0.0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00
334,2817,Midfielder,Premier League,T. George,Everton,19,184,1,3.0,1,1,0.20,0.0,0.26,2,1,2,0,1,5,50,41,4,3,1,6,0.0,0.49,0.49,2,0.98,1.47,0.49,2.45,24.46,20.05,1.96,1.47,0.49,2.93,0.98,0.49,0.98,0.00,0.49,0.0,0.10,0.0,0.13
335,2818,Midfielder,Premier League,C. Olusesi,Tottenham Hotspur,14,0,0,0.0,0,0,0.00,0.0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00

In [20]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/PLcomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [21]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [22]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [23]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.0,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.0,308.000000
mean,2648.915584,28.711039,1658.428571,1.801948,21.730519,7.746753,2.503247,2.488019,0.0,1.599545,29.295455,37.064935,13.314935,21.948052,6.305195,83.337662,766.844156,646.224026,75.399351,28.435065,3.357143,16.493506,4.899351,0.116494,0.084188,4.305195,0.201104,1.125682,0.383896,4.626201,41.753539,35.283571,3.928279,1.471558,0.164773,0.848182,1.671039,1.998571,0.731104,1.207403,0.330552,0.251331,0.124091,0.0,0.080325
std,97.863859,8.630920,995.264745,2.608505,25.179786,10.511704,4.160070,3.722935,0.0,1.883820,25.366250,41.340908,12.980122,24.207516,7.726032,60.199259,562.519207,499.568738,110.413347,40.877018,4.432158,18.150922,20.053177,0.161098,0.111722,6.128725,0.231877,0.984103,0.406598,1.946411,15.952699,15.661288,4.104194,1.702896,0.189141,0.684111,1.010118,1.555361,0.548397,0.987155,0.328651,0.857307,0.144254,0.0,0.074146
min,2483.000000,4.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,24.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.160000,11.990000,7.440000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,2561.750000,23.000000,761.250000,0.000000,4.000000,1.000000,0.000000,0.250000,0.0,0.207500,10.000000,10.000000,3.000000,6.000000,1.000000,28.750000,288.250000,228.000000,15.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,0.070000,3.655000,29.650000,22.450000,1.502500,0.150000,0.000000,0.310000,0.997500,0.760000,0.297500,0.450000,0.070000,0.000000,0.030000,0.0,0.020000
50%,2647.500000,32.000000,1700.000000,1.000000,12.000000,4.000000,1.000000,0.985000,0.0,0.940000,23.000000,23.500000,9.000000,13.000000,3.000000,77.000000,689.500000,573.000000,38.000000,10.000000,2.000000,10.000000,0.000000,0.050000,0.030000,2.000000,0.120000,0.810000,0.235000,4.695000,40.850000,34.125000,2.770000,0.730000,0.110000,0.730000,1.530000,1.510000,0.685000,0.900000,0.245000,0.000000,0.070000,0.0,0.060000
75%,2734.500000,36.000000,2521.250000,3.000000,32.250000,11.000000,3.000000,3.167500,0.0,2.270000,43.000000,48.000000,20.000000,27.000000,9.000000,129.000000,1081.000000,893.750000,88.000000,38.250000,5.000000,24.250000,0.000000,0.172500,0.140000,6.000000,0.330000,1.707500,0.582500,5.755000,52.895000,46.670000,4.857500,2.412500,0.252500,1.310000,2.282500,2.852500,1.030000,1.812500,0.512500,0.000000,0.160000,0.0,0.120000
max,2817.000000,38.000000,3420.000000,18.000000,130.000000,61.000000,29.000000,25.370000,0.0,9.260000,133.000000,220.000000,66.000000,148.000000,44.000000,243.000000,2922.000000,2679.000000,886.000000,202.000000,27.000000,91.000000,125.000000,0.770000,0.520000,47.000000,1.250000,3.880000,1.970000,13.100000,91.430000,85.720000,26.250000,10.710000,1.140000,3.160000,6.170000,7.470000,3.460000,5.780000,1.600000,4.800000,0.720000,0.0,0.400000

In [24]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/PLcomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [25]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [26]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.0,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.00000,341.000000,341.000000,341.000000,341.00000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.000000,341.0,341.000000
mean,2653.000000,26.571848,1499.137830,1.627566,19.636364,7.000000,2.260997,2.248563,0.0,1.446393,26.495601,33.504399,12.035191,19.835777,5.697947,75.354839,693.243402,584.205279,68.13783,25.727273,3.032258,14.914956,4.42522,0.105220,0.076041,3.888563,0.181642,1.036276,0.350528,4.904575,41.786422,34.962933,3.628739,1.432053,0.148827,0.796804,1.876774,1.870792,0.671173,1.385543,0.308710,0.227009,0.114545,0.0,0.076569
std,98.582453,10.701497,1063.941579,2.535455,24.769817,10.246664,4.021915,3.612773,0.0,1.850418,25.581774,40.766669,12.941222,23.893686,7.573151,62.200957,580.035726,511.238829,107.24541,39.717963,4.327289,17.911591,19.11031,0.156918,0.109049,5.961584,0.228241,0.998082,0.405518,6.923560,36.665331,28.140742,4.103829,1.794208,0.186231,0.715840,4.942803,1.647580,0.571903,4.936205,0.368968,0.818032,0.145085,0.0,0.077719
min,2483.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,2568.000000,20.000000,481.000000,0.000000,2.000000,0.000000,0.000000,0.120000,0.0,0.090000,5.000000,6.000000,2.000000,4.000000,0.000000,16.000000,190.000000,158.000000,10.00000,1.000000,0.000000,2.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.270000,0.000000,3.410000,27.600000,21.470000,1.090000,0.080000,0.000000,0.190000,0.860000,0.630000,0.210000,0.370000,0.000000,0.000000,0.010000,0.0,0.020000
50%,2653.000000,30.000000,1533.000000,0.000000,10.000000,3.000000,1.000000,0.770000,0.0,0.690000,19.000000,19.000000,8.000000,11.000000,3.000000,64.000000,598.000000,492.000000,32.00000,7.000000,1.000000,8.000000,0.00000,0.030000,0.000000,1.000000,0.100000,0.750000,0.200000,4.580000,38.980000,32.280000,2.520000,0.600000,0.090000,0.650000,1.490000,1.360000,0.590000,0.820000,0.200000,0.000000,0.060000,0.0,0.050000
75%,2738.000000,36.000000,2440.000000,2.000000,28.000000,9.000000,3.000000,2.700000,0.0,2.040000,39.000000,45.000000,19.000000,25.000000,8.000000,122.000000,1038.000000,857.000000,83.00000,30.000000,4.000000,22.000000,0.00000,0.150000,0.130000,5.000000,0.290000,1.600000,0.530000,5.740000,52.500000,45.920000,4.720000,2.390000,0.240000,1.280000,2.280000,2.790000,1.020000,1.760000,0.470000,0.000000,0.140000,0.0,0.120000
max,2823.000000,38.000000,3420.000000,18.000000,130.000000,61.000000,29.000000,25.370000,0.0,9.260000,133.000000,220.000000,66.000000,148.000000,44.000000,243.000000,2922.000000,2679.000000,886.00000,202.000000,27.000000,91.000000,125.00000,0.770000,0.520000,47.000000,1.250000,3.880000,1.970000,90.000000,450.000000,360.000000,26.250000,10.710000,1.140000,3.460000,90.000000,9.470000,3.460000,90.000000,3.460000,4.800000,0.720000,0.0,0.440000

In [27]:
#We can see that the 25% cutoff is 481
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 481].index)

In [28]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90,xgPer90,npxgPer90,xaPer90
count,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.0,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.0,255.000000
mean,2650.368627,30.882353,1948.521569,2.141176,25.682353,9.211765,2.988235,2.946039,0.0,1.897686,34.231373,43.513725,15.615686,25.729412,7.423529,97.701961,901.200000,759.576471,88.576471,33.658824,3.988235,19.521569,5.729412,0.130510,0.092039,5.129412,0.223059,1.163451,0.412118,4.562863,41.976510,35.565059,3.834196,1.509961,0.176118,0.876588,1.626039,2.027059,0.725765,1.197529,0.335529,0.240118,0.130510,0.0,0.084510
std,99.487572,6.764448,838.592568,2.739991,25.938546,10.989000,4.416756,3.935245,0.0,1.939678,25.132041,42.614261,13.093597,24.925111,8.026594,56.194591,525.246949,475.036767,116.962445,43.076901,4.621486,18.543377,21.893652,0.164089,0.106947,6.428507,0.230692,0.966535,0.405988,1.850909,15.657788,15.454105,3.914082,1.658457,0.179898,0.675355,0.939715,1.573340,0.491628,0.932259,0.305329,0.836109,0.148393,0.0,0.073547
min,2484.000000,10.000000,486.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,96.000000,60.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.160000,11.990000,7.440000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,2560.500000,27.000000,1245.000000,0.000000,7.000000,2.000000,0.000000,0.475000,0.0,0.480000,15.000000,14.000000,6.000000,9.000000,2.000000,50.000000,516.000000,424.500000,24.000000,3.500000,1.000000,6.000000,0.000000,0.000000,0.000000,1.000000,0.040000,0.445000,0.110000,3.680000,29.765000,23.130000,1.470000,0.185000,0.035000,0.345000,0.990000,0.775000,0.345000,0.460000,0.110000,0.000000,0.030000,0.0,0.030000
50%,2645.000000,33.000000,1913.000000,1.000000,17.000000,5.000000,1.000000,1.320000,0.0,1.260000,30.000000,29.000000,13.000000,17.000000,5.000000,101.000000,809.000000,661.000000,52.000000,14.000000,2.000000,14.000000,0.000000,0.060000,0.060000,3.000000,0.150000,0.830000,0.260000,4.610000,41.040000,34.620000,2.770000,0.860000,0.120000,0.730000,1.520000,1.540000,0.730000,0.900000,0.250000,0.000000,0.070000,0.0,0.070000
75%,2740.500000,36.000000,2611.000000,3.000000,38.500000,13.000000,4.000000,3.975000,0.0,2.700000,47.000000,53.500000,22.500000,34.500000,11.000000,137.500000,1195.500000,993.500000,107.000000,52.500000,6.000000,28.000000,0.000000,0.185000,0.150000,8.000000,0.350000,1.765000,0.640000,5.525000,53.470000,45.975000,4.755000,2.485000,0.270000,1.340000,2.210000,2.920000,1.020000,1.800000,0.490000,0.000000,0.190000,0.0,0.130000
max,2814.000000,38.000000,3420.000000,18.000000,130.000000,61.000000,29.000000,25.370000,0.0,9.260000,133.000000,220.000000,66.000000,148.000000,44.000000,243.000000,2922.000000,2679.000000,886.000000,202.000000,27.000000,91.000000,125.000000,0.770000,0.520000,47.000000,1.250000,3.810000,1.970000,13.100000,91.430000,85.720000,23.320000,6.870000,1.090000,3.160000,5.000000,7.470000,2.470000,5.780000,1.420000,4.170000,0.720000,0.0,0.400000

In [29]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/PLcomplete25.csv")