Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2defenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2defenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2defenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2defenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2forwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2forwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2forwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2forwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2goalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2goalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2goalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2goalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2goalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2midfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2midfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2midfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2midfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name              0
Team              0
Tackles           0
Clearances        0
Interceptions     0
aerialsWon        0
Blocks            0
Mins              0
duelsWon          0
unnamed          41
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,0.0
mean,3.926829,9.609756,2.682927,3.682927,0.512195,223.170732,10.170732,NaN
std,4.149640,9.262500,2.769829,4.113630,0.869539,166.391842,8.734708,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,0.000000,2.000000,0.000000,0.000000,0.000000,75.000000,4.000000,NaN
50%,3.000000,7.000000,2.000000,2.000000,0.000000,237.000000,9.000000,NaN
75%,6.000000,18.000000,5.000000,5.000000,1.000000,360.000000,17.000000,NaN
max,21.000000,33.000000,9.000000,18.000000,4.000000,450.000000,40.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 1941)
dfDdef["ID"] = (dfDdef.index + 1941)
dfDatt["ID"] = (dfDatt.index + 1941)
dfDpas["ID"] = (dfDpas.index + 1941) #should end at id no 1981
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 2015
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 2032
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 2074
dfMdft.head(300) #to check final id number

                     Name                Team  App  Mins    ID
0                M. Paulo   Académica Coimbra    6   493  2033
1               A. Castro          FC Porto B    5    23  2034
2             D. Candeias   Académica Coimbra    2   172  2035
3               A. Santos           Varzim SC    3   247  2036
4                A. André          Leixões SC    4   279  2037
5               J. Amorim          Leixões SC    3     0  2038
6                R. Pinto            CD Mafra    4   132  2039
7                 P. Tiba              Chaves    3     0  2040
8               A. Simões          Leixões SC    4   154  2041
9              LSL. Silva  Académico Viseu FC    1    32  2042
10         VGV. Gonçalves            CD Mafra    3   143  2043
11                   Reko            Penafiel    3   124  2044
12              Y. Semedo          SC Farense    5   438  2045
13              H. Evrard          Leixões SC    4   184  2046
14            C. Kahraman  Académico Viseu FC    4   166  2047
15               Paulinho          Leixões SC    3    64  2048
16              A. Ceitil  Académico Viseu FC    5   272  2049
17                 Ktatau              Chaves    4    57  2050
18                H. Jocu            Feirense    2    29  2051
19                Robinho  Académico Viseu FC    1    90  2052
20             D. Andrade          FC Porto B    3   270  2053
21           S. Messeguem  Académico Viseu FC    4   241  2054
22              A. Marcus  CF Estrela Amadora    5   368  2055
23               P. Pinho              Chaves    5   388  2056
24                S. Koné  Académico Viseu FC    4    87  2057
25               N. Félix       Benfica B U21    2   158  2058
26           DPD. Prioste       Benfica B U21    1    30  2059
27              Marquinho  Académico Viseu FC    3   270  2060
28             T. Ribeiro            Feirense    6    79  2061
29  TdT. de Sousa Moreira       Benfica B U21    2     5  2062
30               Cascavel   Académica Coimbra    5    24  2063
31              F. França           Varzim SC    4   118  2064
32            J. Teixeira          FC Porto B    5   331  2065
33               G. Sousa          FC Porto B    5   129  2066
34              K. Nagata          FC Porto B    3   220  2067
35                 Andrey            CD Mafra    1     0  2068
36                R. Pina          Leixões SC    5   351  2069
37               A. Silva            Penafiel    2    99  2070
38           S. Iheanacho            CD Mafra    5   336  2071
39               B. Souza   Académica Coimbra    4     5  2072
40               Y. Maiga            CD Mafra    3   155  2073
41           SPS. Popoola            Feirense    1     0  2074

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2defender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2forward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2goalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/ligaportugal2/LIGAP2midfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,P. Mota,Leixões SC,3,216,1941,0,2.0,1,1,0.0,NaN,0.0,2,7,2,2,0,5,68,55,8,21,0,0,Defender,NaN
1,Kaka,Académica Coimbra,3,0,1942,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Defender,NaN
2,R. Alves,Chaves,5,450,1943,0,4.0,3,2,0.0,NaN,0.0,5,33,4,18,1,24,161,127,32,2,0,1,Defender,NaN
3,H. Basto,CD Trofense,3,257,1944,0,1.0,0,0,0.0,NaN,0.0,4,18,1,5,1,9,82,63,9,0,0,0,Defender,NaN
4,R. Rossi,CD Mafra,5,450,1945,0,3.0,0,0,0.0,NaN,0.0,4,26,6,12,0,18,206,169,39,0,0,2,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,A. Silva,Penafiel,2,99,2070,0,5.0,1,1,0.0,NaN,0.0,1,2,0,0,2,5,17,10,0,2,0,2,Midfielder,NaN
130,S. Iheanacho,CD Mafra,5,336,2071,0,9.0,4,0,0.0,NaN,0.0,6,2,2,4,2,18,63,41,6,2,0,4,Midfielder,NaN
131,B. Souza,Académica Coimbra,4,5,2072,0,NaN,0,0,0.0,NaN,0.0,1,0,0,0,0,1,2,2,0,0,0,0,Midfielder,NaN
132,Y. Maiga,CD Mafra,3,155,2073,0,1.0,0,0,0.0,NaN,0.0,4,3,7,4,0,13,52,35,12,1,0,0,Midfielder,NaN
133,SPS. Popoola,Feirense,1,0,2074,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,P. Mota,Leixões SC,3,216,1941,0,2.0,1,1,0.0,0.0,0.0,2,7,2,2,0,5,68,55,8,21,0,0,Defender,0.0
1,Kaka,Académica Coimbra,3,0,1942,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Defender,0.0
2,R. Alves,Chaves,5,450,1943,0,4.0,3,2,0.0,0.0,0.0,5,33,4,18,1,24,161,127,32,2,0,1,Defender,0.0
3,H. Basto,CD Trofense,3,257,1944,0,1.0,0,0,0.0,0.0,0.0,4,18,1,5,1,9,82,63,9,0,0,0,Defender,0.0
4,R. Rossi,CD Mafra,5,450,1945,0,3.0,0,0,0.0,0.0,0.0,4,26,6,12,0,18,206,169,39,0,0,2,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,J. Teixeira,FC Porto B,5,331,2065,1,6.0,2,0,0.0,0.0,0.0,8,4,4,5,0,25,112,86,10,1,1,4,Midfielder,0.0
125,G. Sousa,FC Porto B,5,129,2066,0,0.0,0,0,0.0,0.0,0.0,4,1,0,1,0,8,49,35,4,6,0,1,Midfielder,0.0
126,K. Nagata,FC Porto B,3,220,2067,0,8.0,3,1,0.0,0.0,0.0,3,1,0,0,3,12,53,44,5,3,0,0,Midfielder,0.0
127,Andrey,CD Mafra,1,0,2068,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
128,R. Pina,Leixões SC,5,351,2069,1,14.0,4,2,0.0,0.0,0.0,1,1,1,3,6,13,139,112,14,4,0,5,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,1941,Defender,P. Mota,Leixões SC,3,216,0,2.0,1,1,0.0,0.0,0.0,2,7,2,2,0,5,68,55,8,21,0,0,0.0
1,1942,Defender,Kaka,Académica Coimbra,3,0,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
2,1943,Defender,R. Alves,Chaves,5,450,0,4.0,3,2,0.0,0.0,0.0,5,33,4,18,1,24,161,127,32,2,0,1,0.0
3,1944,Defender,H. Basto,CD Trofense,3,257,0,1.0,0,0,0.0,0.0,0.0,4,18,1,5,1,9,82,63,9,0,0,0,0.0
4,1945,Defender,R. Rossi,CD Mafra,5,450,0,3.0,0,0,0.0,0.0,0.0,4,26,6,12,0,18,206,169,39,0,0,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2065,Midfielder,J. Teixeira,FC Porto B,5,331,1,6.0,2,0,0.0,0.0,0.0,8,4,4,5,0,25,112,86,10,1,1,4,0.0
125,2066,Midfielder,G. Sousa,FC Porto B,5,129,0,0.0,0,0,0.0,0.0,0.0,4,1,0,1,0,8,49,35,4,6,0,1,0.0
126,2067,Midfielder,K. Nagata,FC Porto B,3,220,0,8.0,3,1,0.0,0.0,0.0,3,1,0,0,3,12,53,44,5,3,0,0,0.0
127,2068,Midfielder,Andrey,CD Mafra,1,0,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
128,2069,Midfielder,R. Pina,Leixões SC,5,351,1,14.0,4,2,0.0,0.0,0.0,1,1,1,3,6,13,139,112,14,4,0,5,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.0,134.0,134.0,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000
mean,2007.500000,3.402985,169.208955,0.134328,1.776119,0.559701,0.149254,0.0,0.0,0.0,2.388060,4.589552,1.373134,2.552239,0.544776,7.955224,62.447761,47.888060,10.708955,3.932836,0.194030,1.492537,0.544776
std,38.826537,1.467028,153.008235,0.383711,2.719027,1.065602,0.482903,0.0,0.0,0.0,3.297095,6.859725,2.175294,3.517020,1.066338,8.301522,65.861505,53.488339,15.885788,7.889460,0.618968,2.545071,2.448310
min,1941.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1974.250000,2.000000,22.250000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.250000,4.500000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2007.500000,4.000000,130.500000,0.000000,1.000000,0.000000,0.000000,0.0,0.0,0.0,1.000000,2.000000,0.000000,1.000000,0.000000,5.000000,43.000000,31.500000,5.000000,0.000000,0.000000,0.000000,0.000000
75%,2040.750000,5.000000,282.000000,0.000000,2.750000,1.000000,0.000000,0.0,0.0,0.0,4.000000,5.000000,2.000000,4.000000,1.000000,13.000000,99.000000,74.250000,14.000000,3.000000,0.000000,2.000000,0.000000
max,2074.000000,7.000000,493.000000,2.000000,14.000000,5.000000,3.000000,0.0,0.0,0.0,21.000000,33.000000,9.000000,19.000000,6.000000,40.000000,311.000000,245.000000,91.000000,44.000000,4.000000,20.000000,16.000000

There are no expected stats captured within this dataset, so we remove them

In [16]:
finalData = finalData.drop(columns=["xG", "npxG", "xA"])

Adding additional data fields

In [17]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90


finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,1941,Defender,P. Mota,Leixões SC,3,216,0,2.0,1,1,2,7,2,2,0,5,68,55,8,21,0,0,0.0,0.416667,0.000000,1,0.416667,0.833333,0.416667,2.083333,28.333333,22.916667,3.333333,8.750000,0.000000,0.000000,0.833333,2.916667,0.833333,0.833333,0.000000,0.0
1,1942,Defender,Kaka,Académica Coimbra,3,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1943,Defender,R. Alves,Chaves,5,450,0,4.0,3,2,5,33,4,18,1,24,161,127,32,2,0,1,0.0,0.400000,0.000000,2,0.400000,0.800000,0.600000,4.800000,32.200000,25.400000,6.400000,0.400000,0.000000,0.200000,1.000000,6.600000,0.800000,3.600000,0.200000,0.0
3,1944,Defender,H. Basto,CD Trofense,3,257,0,1.0,0,0,4,18,1,5,1,9,82,63,9,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.350195,0.000000,3.151751,28.715953,22.062257,3.151751,0.000000,0.000000,0.000000,1.400778,6.303502,0.350195,1.750973,0.350195,0.0
4,1945,Defender,R. Rossi,CD Mafra,5,450,0,3.0,0,0,4,26,6,12,0,18,206,169,39,0,0,2,0.0,0.000000,0.000000,0,0.000000,0.600000,0.000000,3.600000,41.200000,33.800000,7.800000,0.000000,0.000000,0.400000,0.800000,5.200000,1.200000,2.400000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2065,Midfielder,J. Teixeira,FC Porto B,5,331,1,6.0,2,0,8,4,4,5,0,25,112,86,10,1,1,4,0.0,0.000000,0.271903,1,0.271903,1.631420,0.543807,6.797583,30.453172,23.383686,2.719033,0.271903,0.271903,1.087613,2.175227,1.087613,1.087613,1.359517,0.000000,0.0
125,2066,Midfielder,G. Sousa,FC Porto B,5,129,0,0.0,0,0,4,1,0,1,0,8,49,35,4,6,0,1,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,5.581395,34.186047,24.418605,2.790698,4.186047,0.000000,0.697674,2.790698,0.697674,0.000000,0.697674,0.000000,0.0
126,2067,Midfielder,K. Nagata,FC Porto B,3,220,0,8.0,3,1,3,1,0,0,3,12,53,44,5,3,0,0,0.0,0.409091,0.000000,1,0.409091,3.272727,1.227273,4.909091,21.681818,18.000000,2.045455,1.227273,0.000000,0.000000,1.227273,0.409091,0.000000,0.000000,1.227273,0.0
127,2068,Midfielder,Andrey,CD Mafra,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,2069,Midfielder,R. Pina,Leixões SC,5,351,1,14.0,4,2,1,1,1,3,6,13,139,112,14,4,0,5,0.0,0.512821,0.256410,3,0.769231,3.589744,1.025641,3.333333,35.641026,28.717949,3.589744,1.025641,0.000000,1.282051,0.256410,0.256410,0.256410,0.769231,1.538462,0.0

Removing NaN again and fixing decimal places

In [18]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,1941,Defender,P. Mota,Leixões SC,3,216,0,2.0,1,1,2,7,2,2,0,5,68,55,8,21,0,0,0.0,0.42,0.00,1,0.42,0.83,0.42,2.08,28.33,22.92,3.33,8.75,0.00,0.00,0.83,2.92,0.83,0.83,0.00,0.0
1,1942,Defender,Kaka,Académica Coimbra,3,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2,1943,Defender,R. Alves,Chaves,5,450,0,4.0,3,2,5,33,4,18,1,24,161,127,32,2,0,1,0.0,0.40,0.00,2,0.40,0.80,0.60,4.80,32.20,25.40,6.40,0.40,0.00,0.20,1.00,6.60,0.80,3.60,0.20,0.0
3,1944,Defender,H. Basto,CD Trofense,3,257,0,1.0,0,0,4,18,1,5,1,9,82,63,9,0,0,0,0.0,0.00,0.00,0,0.00,0.35,0.00,3.15,28.72,22.06,3.15,0.00,0.00,0.00,1.40,6.30,0.35,1.75,0.35,0.0
4,1945,Defender,R. Rossi,CD Mafra,5,450,0,3.0,0,0,4,26,6,12,0,18,206,169,39,0,0,2,0.0,0.00,0.00,0,0.00,0.60,0.00,3.60,41.20,33.80,7.80,0.00,0.00,0.40,0.80,5.20,1.20,2.40,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2065,Midfielder,J. Teixeira,FC Porto B,5,331,1,6.0,2,0,8,4,4,5,0,25,112,86,10,1,1,4,0.0,0.00,0.27,1,0.27,1.63,0.54,6.80,30.45,23.38,2.72,0.27,0.27,1.09,2.18,1.09,1.09,1.36,0.00,0.0
125,2066,Midfielder,G. Sousa,FC Porto B,5,129,0,0.0,0,0,4,1,0,1,0,8,49,35,4,6,0,1,0.0,0.00,0.00,0,0.00,0.00,0.00,5.58,34.19,24.42,2.79,4.19,0.00,0.70,2.79,0.70,0.00,0.70,0.00,0.0
126,2067,Midfielder,K. Nagata,FC Porto B,3,220,0,8.0,3,1,3,1,0,0,3,12,53,44,5,3,0,0,0.0,0.41,0.00,1,0.41,3.27,1.23,4.91,21.68,18.00,2.05,1.23,0.00,0.00,1.23,0.41,0.00,0.00,1.23,0.0
127,2068,Midfielder,Andrey,CD Mafra,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
128,2069,Midfielder,R. Pina,Leixões SC,5,351,1,14.0,4,2,1,1,1,3,6,13,139,112,14,4,0,5,0.0,0.51,0.26,3,0.77,3.59,1.03,3.33,35.64,28.72,3.59,1.03,0.00,1.28,0.26,0.26,0.26,0.77,1.54,0.0

Adding and moving "League" column

In [19]:
#label
leagueLabel = "Liga Portugal 2"

#adding label to df
finalData["League"] = leagueLabel

In [20]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,1941,Defender,Liga Portugal 2,P. Mota,Leixões SC,3,216,0,2.0,1,1,2,7,2,2,0,5,68,55,8,21,0,0,0.0,0.42,0.00,1,0.42,0.83,0.42,2.08,28.33,22.92,3.33,8.75,0.00,0.00,0.83,2.92,0.83,0.83,0.00,0.0
1,1942,Defender,Liga Portugal 2,Kaka,Académica Coimbra,3,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
2,1943,Defender,Liga Portugal 2,R. Alves,Chaves,5,450,0,4.0,3,2,5,33,4,18,1,24,161,127,32,2,0,1,0.0,0.40,0.00,2,0.40,0.80,0.60,4.80,32.20,25.40,6.40,0.40,0.00,0.20,1.00,6.60,0.80,3.60,0.20,0.0
3,1944,Defender,Liga Portugal 2,H. Basto,CD Trofense,3,257,0,1.0,0,0,4,18,1,5,1,9,82,63,9,0,0,0,0.0,0.00,0.00,0,0.00,0.35,0.00,3.15,28.72,22.06,3.15,0.00,0.00,0.00,1.40,6.30,0.35,1.75,0.35,0.0
4,1945,Defender,Liga Portugal 2,R. Rossi,CD Mafra,5,450,0,3.0,0,0,4,26,6,12,0,18,206,169,39,0,0,2,0.0,0.00,0.00,0,0.00,0.60,0.00,3.60,41.20,33.80,7.80,0.00,0.00,0.40,0.80,5.20,1.20,2.40,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,2065,Midfielder,Liga Portugal 2,J. Teixeira,FC Porto B,5,331,1,6.0,2,0,8,4,4,5,0,25,112,86,10,1,1,4,0.0,0.00,0.27,1,0.27,1.63,0.54,6.80,30.45,23.38,2.72,0.27,0.27,1.09,2.18,1.09,1.09,1.36,0.00,0.0
125,2066,Midfielder,Liga Portugal 2,G. Sousa,FC Porto B,5,129,0,0.0,0,0,4,1,0,1,0,8,49,35,4,6,0,1,0.0,0.00,0.00,0,0.00,0.00,0.00,5.58,34.19,24.42,2.79,4.19,0.00,0.70,2.79,0.70,0.00,0.70,0.00,0.0
126,2067,Midfielder,Liga Portugal 2,K. Nagata,FC Porto B,3,220,0,8.0,3,1,3,1,0,0,3,12,53,44,5,3,0,0,0.0,0.41,0.00,1,0.41,3.27,1.23,4.91,21.68,18.00,2.05,1.23,0.00,0.00,1.23,0.41,0.00,0.00,1.23,0.0
127,2068,Midfielder,Liga Portugal 2,Andrey,CD Mafra,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
128,2069,Midfielder,Liga Portugal 2,R. Pina,Leixões SC,5,351,1,14.0,4,2,1,1,1,3,6,13,139,112,14,4,0,5,0.0,0.51,0.26,3,0.77,3.59,1.03,3.33,35.64,28.72,3.59,1.03,0.00,1.28,0.26,0.26,0.26,0.77,1.54,0.0

In [21]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/LIGAP2complete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [22]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [23]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [24]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000
mean,2005.049383,3.950617,265.111111,0.222222,2.740741,0.851852,0.246914,3.580247,7.345679,2.209877,3.962963,0.851852,11.938272,97.296296,74.580247,17.148148,5.567901,0.296296,2.209877,0.901235,0.093333,0.062346,0.469136,0.155432,0.909753,0.301975,4.042346,31.813457,24.079506,5.688272,1.762716,0.092222,0.673086,1.200617,2.349753,0.708519,1.306543,0.280741,0.268765
std,41.173991,1.171551,121.719555,0.474342,3.093452,1.256096,0.602720,3.683966,7.640616,2.453141,3.874418,1.266009,8.280015,63.320700,53.601274,17.653690,9.514382,0.749074,3.007142,3.104855,0.241475,0.133110,0.775990,0.270518,0.965668,0.434481,2.171275,11.574494,10.739857,4.564379,2.559387,0.219072,0.753281,1.136675,2.125363,0.781713,1.055978,0.441553,0.794732
min,1941.000000,1.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.280000,4.970000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1966.000000,3.000000,161.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,1.000000,0.000000,5.000000,51.000000,36.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.650000,24.700000,17.200000,2.620000,0.000000,0.000000,0.000000,0.330000,0.970000,0.000000,0.570000,0.000000,0.000000
50%,2003.000000,4.000000,267.000000,0.000000,2.000000,0.000000,0.000000,2.000000,4.000000,1.000000,3.000000,0.000000,11.000000,80.000000,61.000000,12.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.670000,0.000000,3.630000,31.960000,22.920000,4.560000,0.460000,0.000000,0.600000,1.000000,1.680000,0.550000,1.000000,0.000000,0.000000
75%,2043.000000,5.000000,360.000000,0.000000,4.000000,1.000000,0.000000,6.000000,10.000000,4.000000,5.000000,1.000000,18.000000,135.000000,104.000000,20.000000,5.000000,0.000000,4.000000,0.000000,0.000000,0.000000,1.000000,0.280000,1.390000,0.540000,5.070000,36.440000,28.000000,7.530000,2.900000,0.000000,1.070000,1.710000,3.310000,1.140000,1.890000,0.460000,0.000000
max,2073.000000,6.000000,493.000000,2.000000,14.000000,5.000000,3.000000,21.000000,33.000000,9.000000,19.000000,6.000000,40.000000,311.000000,245.000000,91.000000,44.000000,4.000000,20.000000,16.000000,1.270000,0.520000,3.000000,1.270000,4.550000,2.110000,8.960000,68.350000,59.240000,21.000000,8.800000,1.050000,4.110000,5.840000,10.000000,4.060000,4.000000,2.280000,3.200000

In [25]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/LIGAP2complete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [26]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [27]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000
mean,2007.500000,3.402985,169.208955,0.134328,1.776119,0.559701,0.149254,2.388060,4.589552,1.373134,2.552239,0.544776,7.955224,62.447761,47.888060,10.708955,3.932836,0.194030,1.492537,0.544776,0.056418,0.037687,0.283582,0.093955,0.819328,0.298806,4.853955,27.921269,20.973582,4.087239,2.487388,0.077761,0.662388,1.262463,1.867463,0.494104,1.340149,0.231716,0.162463
std,38.826537,1.467028,153.008235,0.383711,2.719027,1.065602,0.482903,3.297095,6.859725,2.175294,3.517020,1.066338,8.301522,65.861505,53.488339,15.885788,7.889460,0.618968,2.545071,2.448310,0.192801,0.107675,0.644373,0.223243,1.355406,0.945739,8.816742,18.405734,15.915008,4.488887,6.064297,0.305594,1.067540,2.098014,2.611943,0.751871,3.581020,0.548642,0.630324
min,1941.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1974.250000,2.000000,22.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.250000,4.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.285000,11.520000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2007.500000,4.000000,130.500000,0.000000,1.000000,0.000000,0.000000,1.000000,2.000000,0.000000,1.000000,0.000000,5.000000,43.000000,31.500000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.235000,0.000000,3.550000,29.915000,21.000000,3.100000,0.000000,0.000000,0.000000,0.640000,1.085000,0.000000,0.755000,0.000000,0.000000
75%,2040.750000,5.000000,282.000000,0.000000,2.750000,1.000000,0.000000,4.000000,5.000000,2.000000,4.000000,1.000000,13.000000,99.000000,74.250000,14.000000,3.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.140000,0.337500,5.680000,36.187500,27.540000,5.777500,2.857500,0.000000,1.022500,1.700000,2.235000,0.907500,1.655000,0.250000,0.000000
max,2074.000000,7.000000,493.000000,2.000000,14.000000,5.000000,3.000000,21.000000,33.000000,9.000000,19.000000,6.000000,40.000000,311.000000,245.000000,91.000000,44.000000,4.000000,20.000000,16.000000,1.270000,0.520000,3.000000,1.270000,10.000000,10.000000,90.000000,101.740000,86.090000,21.000000,53.180000,2.950000,7.830000,18.000000,18.000000,4.060000,40.000000,4.500000,3.200000

In [28]:
#We can see that the 25% cutoff is 22.5, so we round up to 23
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 23].index)

In [29]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.00000,98.000000,98.000000,98.000000,98.000000,98.000000
mean,2007.173469,3.857143,229.571429,0.183673,2.397959,0.755102,0.204082,3.224490,6.244898,1.877551,3.418367,0.734694,10.683673,84.612245,64.948980,14.581633,5.122449,0.265306,2.020408,0.744898,0.077143,0.051531,0.387755,0.128469,0.911122,0.306531,4.511939,33.185714,25.550612,5.327857,2.283163,0.106327,0.825816,1.39551,2.175918,0.675612,1.296735,0.270918,0.222143
std,40.882287,1.284323,135.565863,0.438999,2.941841,1.184620,0.555371,3.498249,7.361170,2.351860,3.735932,1.188875,8.127333,63.969489,53.130334,17.012987,8.816883,0.711482,2.791665,2.840471,0.222154,0.123191,0.726986,0.252694,0.998389,0.473136,2.775979,12.862240,12.652195,4.355894,3.484440,0.353522,0.920688,1.48047,2.045059,0.806984,1.153933,0.451641,0.728951
min,1941.000000,1.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.280000,4.970000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1970.250000,3.000000,104.250000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,4.000000,33.250000,23.750000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.795000,25.460000,18.057500,2.530000,0.000000,0.000000,0.000000,0.26250,0.922500,0.000000,0.430000,0.000000,0.000000
50%,2005.500000,4.000000,213.500000,0.000000,1.000000,0.000000,0.000000,2.000000,3.000000,1.000000,2.000000,0.000000,8.000000,67.000000,44.000000,8.500000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.650000,0.000000,4.135000,32.100000,23.475000,4.300000,0.560000,0.000000,0.640000,1.08000,1.580000,0.495000,1.000000,0.000000,0.000000
75%,2045.750000,5.000000,336.750000,0.000000,3.000000,1.000000,0.000000,5.000000,7.000000,3.000000,5.000000,1.000000,15.750000,118.750000,87.750000,19.000000,4.750000,0.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.200000,1.477500,0.540000,5.925000,37.900000,29.672500,6.992500,3.792500,0.000000,1.215000,2.00000,2.965000,1.140000,2.000000,0.407500,0.000000
max,2073.000000,7.000000,493.000000,2.000000,14.000000,5.000000,3.000000,21.000000,33.000000,9.000000,19.000000,6.000000,40.000000,311.000000,245.000000,91.000000,44.000000,4.000000,20.000000,16.000000,1.270000,0.520000,3.000000,1.270000,4.550000,2.110000,16.000000,78.000000,78.000000,21.000000,17.700000,2.950000,4.110000,8.00000,10.000000,4.060000,5.620000,2.280000,3.200000

In [30]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/LIGAP2complete25.csv")