Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/premiership/PSdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/premiership/PSdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/premiership/PSdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/premiership/PSdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/premiership/PSforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/premiership/PSforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/premiership/PSforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/premiership/PSforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/premiership/PSgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/premiership/PSgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/premiership/PSgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/premiership/PSgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/premiership/PSgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/premiership/PSmidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/premiership/PSmidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/premiership/PSmidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/premiership/PSmidfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name              0
Team              0
Tackles           0
Clearances        0
Interceptions     0
aerialsWon        0
Blocks            0
Mins              0
duelsWon          0
unnamed          53
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,0.0
mean,21.735849,82.490566,14.264151,46.924528,2.094340,1322.943396,81.433962,NaN
std,17.858580,63.535158,13.202784,39.692980,2.467201,918.038009,57.695990,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,9.000000,23.000000,5.000000,12.000000,0.000000,625.000000,37.000000,NaN
50%,19.000000,77.000000,11.000000,37.000000,1.000000,1174.000000,82.000000,NaN
75%,35.000000,122.000000,19.000000,67.000000,3.000000,1990.000000,122.000000,NaN
max,88.000000,247.000000,64.000000,150.000000,13.000000,3150.000000,229.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 2824)
dfDdef["ID"] = (dfDdef.index + 2824)
dfDatt["ID"] = (dfDatt.index + 2824)
dfDpas["ID"] = (dfDpas.index + 2824) #should end at id no 2876
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 2902
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 2920
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 2986
dfMdft.head(300) #to check final id number

            Name           Team  App  Mins    ID
0    A. Halliday     Motherwell   35  2393  2921
1     G. Shinnie       Aberdeen   34  2580  2922
2     J. Forrest         Celtic   20   804  2923
3    C. McGregor         Celtic   32  2661  2924
4        J. Holt  St. Johnstone   28  1926  2925
..           ...            ...  ...   ...   ...
61    K. Andrews      Hibernian   14   470  2982
62   F. Franczak  St. Johnstone   28   368  2983
63  CDC. Donovan         Celtic    1     0  2984
64       B. Rice        Rangers   13   107  2985
65       V. Enem       Aberdeen    5     0  2986

[66 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/premiership/PSdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/premiership/PSforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/premiership/PSgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/premiership/PSmidfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,C. Robertson,Dundee FC,20,1567,2824,0,8.0,4,0,0.0,NaN,0.0,19,136,9,67,2,93,597,440,125,4,0,4,Defender,NaN
1,J. Tavernier,Rangers,31,2518,2825,8,51.0,17,4,0.0,NaN,0.0,55,84,39,54,13,142,1656,1313,218,220,14,66,Defender,NaN
2,M. Fraser,St. Mirren,35,3140,2826,3,9.0,2,0,0.0,NaN,0.0,58,137,39,52,2,152,1127,790,239,43,3,22,Defender,NaN
3,J. Obita,Hibernian,33,1897,2827,5,5.0,1,0,0.0,NaN,0.0,26,73,15,37,2,81,770,556,160,99,8,22,Defender,NaN
4,S. Kingsley,Heart of Midlothian,18,590,2828,0,4.0,1,1,0.0,NaN,0.0,8,19,5,7,0,20,336,285,46,21,1,1,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,K. Andrews,Hibernian,14,470,2982,0,3.0,0,0,0.0,NaN,0.0,11,3,2,4,2,21,187,152,14,0,0,1,Midfielder,NaN
159,F. Franczak,St. Johnstone,28,368,2983,0,2.0,0,0,0.0,NaN,0.0,11,11,3,4,0,23,102,84,4,10,0,3,Midfielder,NaN
160,CDC. Donovan,Celtic,1,0,2984,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
161,B. Rice,Rangers,13,107,2985,0,2.0,1,0,0.0,NaN,0.0,4,1,0,5,1,10,80,66,9,0,0,0,Midfielder,NaN
162,V. Enem,Aberdeen,5,0,2986,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,C. Robertson,Dundee FC,20,1567,2824,0,8.0,4,0,0.0,0.0,0.0,19,136,9,67,2,93,597,440,125,4,0,4,Defender,0.0
1,J. Tavernier,Rangers,31,2518,2825,8,51.0,17,4,0.0,0.0,0.0,55,84,39,54,13,142,1656,1313,218,220,14,66,Defender,0.0
2,M. Fraser,St. Mirren,35,3140,2826,3,9.0,2,0,0.0,0.0,0.0,58,137,39,52,2,152,1127,790,239,43,3,22,Defender,0.0
3,J. Obita,Hibernian,33,1897,2827,5,5.0,1,0,0.0,0.0,0.0,26,73,15,37,2,81,770,556,160,99,8,22,Defender,0.0
4,S. Kingsley,Heart of Midlothian,18,590,2828,0,4.0,1,1,0.0,0.0,0.0,8,19,5,7,0,20,336,285,46,21,1,1,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,FPF. Pollock,Heart of Midlothian,1,0,2977,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
154,A. Denholm,Livingston,16,689,2978,1,8.0,2,0,0.0,0.0,0.0,9,17,6,8,4,37,221,165,27,15,1,9,Midfielder,0.0
155,M. Tait,Heart of Midlothian,7,0,2979,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0
156,R. Allan Molotnikov,Hibernian,23,477,2980,0,7.0,1,0,0.0,0.0,0.0,8,1,0,4,2,30,96,79,3,6,0,2,Midfielder,0.0
157,JWJ. Williamson,Ross County,1,0,2981,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,2824,Defender,C. Robertson,Dundee FC,20,1567,0,8.0,4,0,0.0,0.0,0.0,19,136,9,67,2,93,597,440,125,4,0,4,0.0
1,2825,Defender,J. Tavernier,Rangers,31,2518,8,51.0,17,4,0.0,0.0,0.0,55,84,39,54,13,142,1656,1313,218,220,14,66,0.0
2,2826,Defender,M. Fraser,St. Mirren,35,3140,3,9.0,2,0,0.0,0.0,0.0,58,137,39,52,2,152,1127,790,239,43,3,22,0.0
3,2827,Defender,J. Obita,Hibernian,33,1897,5,5.0,1,0,0.0,0.0,0.0,26,73,15,37,2,81,770,556,160,99,8,22,0.0
4,2828,Defender,S. Kingsley,Heart of Midlothian,18,590,0,4.0,1,1,0.0,0.0,0.0,8,19,5,7,0,20,336,285,46,21,1,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,2977,Midfielder,FPF. Pollock,Heart of Midlothian,1,0,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
154,2978,Midfielder,A. Denholm,Livingston,16,689,1,8.0,2,0,0.0,0.0,0.0,9,17,6,8,4,37,221,165,27,15,1,9,0.0
155,2979,Midfielder,M. Tait,Heart of Midlothian,7,0,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
156,2980,Midfielder,R. Allan Molotnikov,Hibernian,23,477,0,7.0,1,0,0.0,0.0,0.0,8,1,0,4,2,30,96,79,3,6,0,2,0.0
157,2981,Midfielder,JWJ. Williamson,Ross County,1,0,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.0,163.0,163.0,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.00000,163.000000,163.000000
mean,2905.000000,22.435583,1236.398773,1.325153,14.631902,4.815951,1.693252,0.0,0.0,0.0,20.460123,41.073620,9.625767,27.233129,4.453988,66.889571,539.361963,424.263804,81.269939,27.000000,2.07362,11.171779,3.883436
std,47.198164,11.162126,911.458867,1.968528,17.056535,6.378242,2.733720,0.0,0.0,0.0,22.449737,50.953569,11.784634,34.530818,5.783333,60.598660,532.600525,471.997866,98.076379,44.441805,3.17894,13.580394,14.171085
min,2824.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,2864.500000,13.000000,364.000000,0.000000,2.000000,0.000000,0.000000,0.0,0.0,0.0,2.000000,4.000000,1.000000,4.000000,0.000000,12.500000,118.500000,85.000000,9.000000,0.000000,0.00000,1.000000,0.000000
50%,2905.000000,27.000000,1166.000000,0.000000,9.000000,2.000000,1.000000,0.0,0.0,0.0,14.000000,21.000000,5.000000,14.000000,2.000000,52.000000,438.000000,285.000000,48.000000,7.000000,1.00000,6.000000,0.000000
75%,2945.500000,32.000000,1977.000000,2.000000,20.500000,7.000000,2.000000,0.0,0.0,0.0,30.500000,62.500000,15.000000,37.000000,6.000000,107.000000,778.500000,601.000000,117.000000,38.000000,3.00000,15.000000,0.000000
max,2986.000000,35.000000,3150.000000,9.000000,85.000000,36.000000,16.000000,0.0,0.0,0.0,97.000000,247.000000,64.000000,212.000000,27.000000,274.000000,2989.000000,2835.000000,526.000000,220.000000,14.00000,66.000000,75.000000

There are no expected stats captured within this dataset, so we remove them

In [16]:
finalData = finalData.drop(columns=["xG", "npxG", "xA"])

Adding additional data fields

In [17]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90


finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,2824,Defender,C. Robertson,Dundee FC,20,1567,0,8.0,4,0,19,136,9,67,2,93,597,440,125,4,0,4,0.0,0.000000,0.000000,0,0.000000,0.459477,0.229738,5.341417,34.288449,25.271219,7.179324,0.229738,0.000000,0.229738,1.091257,7.811104,0.516911,3.848117,0.114869,0.0
1,2825,Defender,J. Tavernier,Rangers,31,2518,8,51.0,17,4,55,84,39,54,13,142,1656,1313,218,220,14,66,0.0,0.142971,0.285941,12,0.428912,1.822875,0.607625,5.075457,59.189833,46.930103,7.791898,7.863384,0.500397,2.359015,1.965846,3.002383,1.393963,1.930103,0.464654,0.0
2,2826,Defender,M. Fraser,St. Mirren,35,3140,3,9.0,2,0,58,137,39,52,2,152,1127,790,239,43,3,22,0.0,0.000000,0.085987,3,0.085987,0.257962,0.057325,4.356688,32.302548,22.643312,6.850318,1.232484,0.085987,0.630573,1.662420,3.926752,1.117834,1.490446,0.057325,0.0
3,2827,Defender,J. Obita,Hibernian,33,1897,5,5.0,1,0,26,73,15,37,2,81,770,556,160,99,8,22,0.0,0.000000,0.237217,5,0.237217,0.237217,0.047443,3.842910,36.531365,26.378492,7.590933,4.696890,0.379547,1.043753,1.233527,3.463363,0.711650,1.755403,0.094887,0.0
4,2828,Defender,S. Kingsley,Heart of Midlothian,18,590,0,4.0,1,1,8,19,5,7,0,20,336,285,46,21,1,1,0.0,0.152542,0.000000,1,0.152542,0.610169,0.152542,3.050847,51.254237,43.474576,7.016949,3.203390,0.152542,0.152542,1.220339,2.898305,0.762712,1.067797,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,2977,Midfielder,FPF. Pollock,Heart of Midlothian,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,2978,Midfielder,A. Denholm,Livingston,16,689,1,8.0,2,0,9,17,6,8,4,37,221,165,27,15,1,9,0.0,0.000000,0.130624,1,0.130624,1.044993,0.261248,4.833091,28.867925,21.552975,3.526851,1.959361,0.130624,1.175617,1.175617,2.220610,0.783745,1.044993,0.522496,0.0
155,2979,Midfielder,M. Tait,Heart of Midlothian,7,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,2980,Midfielder,R. Allan Molotnikov,Hibernian,23,477,0,7.0,1,0,8,1,0,4,2,30,96,79,3,6,0,2,0.0,0.000000,0.000000,0,0.000000,1.320755,0.188679,5.660377,18.113208,14.905660,0.566038,1.132075,0.000000,0.377358,1.509434,0.188679,0.000000,0.754717,0.377358,0.0
157,2981,Midfielder,JWJ. Williamson,Ross County,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Removing NaN again and fixing decimal places

In [18]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,2824,Defender,C. Robertson,Dundee FC,20,1567,0,8.0,4,0,19,136,9,67,2,93,597,440,125,4,0,4,0.0,0.00,0.00,0,0.00,0.46,0.23,5.34,34.29,25.27,7.18,0.23,0.00,0.23,1.09,7.81,0.52,3.85,0.11,0.0
1,2825,Defender,J. Tavernier,Rangers,31,2518,8,51.0,17,4,55,84,39,54,13,142,1656,1313,218,220,14,66,0.0,0.14,0.29,12,0.43,1.82,0.61,5.08,59.19,46.93,7.79,7.86,0.50,2.36,1.97,3.00,1.39,1.93,0.46,0.0
2,2826,Defender,M. Fraser,St. Mirren,35,3140,3,9.0,2,0,58,137,39,52,2,152,1127,790,239,43,3,22,0.0,0.00,0.09,3,0.09,0.26,0.06,4.36,32.30,22.64,6.85,1.23,0.09,0.63,1.66,3.93,1.12,1.49,0.06,0.0
3,2827,Defender,J. Obita,Hibernian,33,1897,5,5.0,1,0,26,73,15,37,2,81,770,556,160,99,8,22,0.0,0.00,0.24,5,0.24,0.24,0.05,3.84,36.53,26.38,7.59,4.70,0.38,1.04,1.23,3.46,0.71,1.76,0.09,0.0
4,2828,Defender,S. Kingsley,Heart of Midlothian,18,590,0,4.0,1,1,8,19,5,7,0,20,336,285,46,21,1,1,0.0,0.15,0.00,1,0.15,0.61,0.15,3.05,51.25,43.47,7.02,3.20,0.15,0.15,1.22,2.90,0.76,1.07,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,2977,Midfielder,FPF. Pollock,Heart of Midlothian,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
154,2978,Midfielder,A. Denholm,Livingston,16,689,1,8.0,2,0,9,17,6,8,4,37,221,165,27,15,1,9,0.0,0.00,0.13,1,0.13,1.04,0.26,4.83,28.87,21.55,3.53,1.96,0.13,1.18,1.18,2.22,0.78,1.04,0.52,0.0
155,2979,Midfielder,M. Tait,Heart of Midlothian,7,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
156,2980,Midfielder,R. Allan Molotnikov,Hibernian,23,477,0,7.0,1,0,8,1,0,4,2,30,96,79,3,6,0,2,0.0,0.00,0.00,0,0.00,1.32,0.19,5.66,18.11,14.91,0.57,1.13,0.00,0.38,1.51,0.19,0.00,0.75,0.38,0.0
157,2981,Midfielder,JWJ. Williamson,Ross County,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0

Adding and moving "League" column

In [19]:
#label
leagueLabel = "Premiership"

#adding label to df
finalData["League"] = leagueLabel

In [20]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,2824,Defender,Premiership,C. Robertson,Dundee FC,20,1567,0,8.0,4,0,19,136,9,67,2,93,597,440,125,4,0,4,0.0,0.00,0.00,0,0.00,0.46,0.23,5.34,34.29,25.27,7.18,0.23,0.00,0.23,1.09,7.81,0.52,3.85,0.11,0.0
1,2825,Defender,Premiership,J. Tavernier,Rangers,31,2518,8,51.0,17,4,55,84,39,54,13,142,1656,1313,218,220,14,66,0.0,0.14,0.29,12,0.43,1.82,0.61,5.08,59.19,46.93,7.79,7.86,0.50,2.36,1.97,3.00,1.39,1.93,0.46,0.0
2,2826,Defender,Premiership,M. Fraser,St. Mirren,35,3140,3,9.0,2,0,58,137,39,52,2,152,1127,790,239,43,3,22,0.0,0.00,0.09,3,0.09,0.26,0.06,4.36,32.30,22.64,6.85,1.23,0.09,0.63,1.66,3.93,1.12,1.49,0.06,0.0
3,2827,Defender,Premiership,J. Obita,Hibernian,33,1897,5,5.0,1,0,26,73,15,37,2,81,770,556,160,99,8,22,0.0,0.00,0.24,5,0.24,0.24,0.05,3.84,36.53,26.38,7.59,4.70,0.38,1.04,1.23,3.46,0.71,1.76,0.09,0.0
4,2828,Defender,Premiership,S. Kingsley,Heart of Midlothian,18,590,0,4.0,1,1,8,19,5,7,0,20,336,285,46,21,1,1,0.0,0.15,0.00,1,0.15,0.61,0.15,3.05,51.25,43.47,7.02,3.20,0.15,0.15,1.22,2.90,0.76,1.07,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,2977,Midfielder,Premiership,FPF. Pollock,Heart of Midlothian,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
154,2978,Midfielder,Premiership,A. Denholm,Livingston,16,689,1,8.0,2,0,9,17,6,8,4,37,221,165,27,15,1,9,0.0,0.00,0.13,1,0.13,1.04,0.26,4.83,28.87,21.55,3.53,1.96,0.13,1.18,1.18,2.22,0.78,1.04,0.52,0.0
155,2979,Midfielder,Premiership,M. Tait,Heart of Midlothian,7,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
156,2980,Midfielder,Premiership,R. Allan Molotnikov,Hibernian,23,477,0,7.0,1,0,8,1,0,4,2,30,96,79,3,6,0,2,0.0,0.00,0.00,0,0.00,1.32,0.19,5.66,18.11,14.91,0.57,1.13,0.00,0.38,1.51,0.19,0.00,0.75,0.38,0.0
157,2981,Midfielder,Premiership,JWJ. Williamson,Ross County,1,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0

In [21]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/PScomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [22]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [23]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [24]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000
mean,2902.077465,25.126761,1416.788732,1.507042,16.718310,5.500000,1.936620,23.422535,47.091549,11.021127,31.204225,5.098592,76.598592,618.309859,486.401408,93.225352,30.943662,2.366197,12.795775,4.457746,0.122254,0.090493,3.443662,0.212887,1.121690,0.370915,4.860986,38.847535,30.560704,5.920563,1.933380,0.148169,0.814014,1.458451,2.910211,0.646831,1.938873,0.343169,0.305915
std,46.900086,9.142574,836.666908,2.044701,17.322705,6.562034,2.848951,22.590189,51.959327,12.012681,35.306267,5.930221,59.004395,526.474669,475.154727,99.670051,46.342202,3.305870,13.829529,15.104658,0.164960,0.127298,4.306559,0.256002,0.954842,0.399530,2.265267,21.041775,20.941995,5.547078,2.325808,0.192916,0.689318,0.989921,2.631667,0.476852,1.738286,0.377110,0.903899
min,2824.000000,2.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.140000,5.590000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2859.250000,17.250000,694.000000,0.000000,4.000000,1.000000,0.000000,8.000000,9.250000,2.000000,7.000000,1.000000,26.250000,218.000000,153.750000,19.500000,2.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.450000,0.050000,3.825000,26.790000,18.040000,2.202500,0.107500,0.000000,0.230000,0.895000,0.855000,0.290000,0.685000,0.080000,0.000000
50%,2904.500000,29.000000,1333.000000,1.000000,10.500000,3.000000,1.000000,17.000000,26.000000,8.000000,17.000000,3.000000,69.500000,513.500000,372.000000,64.000000,9.500000,1.000000,8.000000,0.000000,0.050000,0.045000,2.000000,0.135000,0.790000,0.240000,4.950000,33.545000,24.285000,4.595000,0.900000,0.085000,0.710000,1.300000,2.065000,0.645000,1.410000,0.240000,0.000000
75%,2941.750000,32.000000,2058.750000,2.000000,23.000000,8.000000,3.000000,34.500000,69.000000,16.000000,45.750000,7.000000,112.750000,818.750000,649.500000,133.000000,43.000000,3.000000,17.750000,0.000000,0.167500,0.127500,5.000000,0.300000,1.797500,0.597500,6.010000,46.367500,37.302500,7.452500,2.635000,0.227500,1.237500,2.010000,4.155000,0.877500,2.810000,0.477500,0.000000
max,2985.000000,35.000000,3150.000000,9.000000,85.000000,36.000000,16.000000,97.000000,247.000000,64.000000,212.000000,27.000000,274.000000,2989.000000,2835.000000,526.000000,220.000000,14.000000,66.000000,75.000000,0.750000,0.750000,23.000000,1.500000,3.960000,1.590000,12.490000,151.000000,145.000000,27.680000,11.240000,0.990000,2.890000,5.690000,10.760000,1.980000,9.670000,1.980000,4.570000

In [25]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/PScomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [26]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [27]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.00000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000,163.000000
mean,2905.000000,22.435583,1236.398773,1.325153,14.631902,4.815951,1.693252,20.460123,41.073620,9.625767,27.233129,4.453988,66.889571,539.361963,424.263804,81.269939,27.000000,2.07362,11.171779,3.883436,0.128589,0.125521,3.018405,0.254233,1.221350,0.430368,4.676012,35.691350,27.946933,5.263497,1.807791,0.175767,0.796626,1.420429,2.621166,0.621411,1.788221,0.377853,0.266503
std,47.198164,11.162126,911.458867,1.968528,17.056535,6.378242,2.733720,22.449737,50.953569,11.784634,34.530818,5.783333,60.598660,532.600525,471.997866,98.076379,44.441805,3.17894,13.580394,14.171085,0.316462,0.493611,4.169958,0.591571,2.002611,0.978181,2.947034,22.608576,21.442911,5.486758,2.373699,0.508698,0.856032,1.256330,2.606519,0.608180,1.854059,0.938403,0.849524
min,2824.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2864.500000,13.000000,364.000000,0.000000,2.000000,0.000000,0.000000,2.000000,4.000000,1.000000,4.000000,0.000000,12.500000,118.500000,85.000000,9.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.325000,0.000000,3.500000,24.895000,14.835000,1.550000,0.000000,0.000000,0.140000,0.645000,0.670000,0.090000,0.500000,0.000000,0.000000
50%,2905.000000,27.000000,1166.000000,0.000000,9.000000,2.000000,1.000000,14.000000,21.000000,5.000000,14.000000,2.000000,52.000000,438.000000,285.000000,48.000000,7.000000,1.00000,6.000000,0.000000,0.030000,0.000000,1.000000,0.110000,0.740000,0.200000,4.870000,32.300000,23.360000,4.250000,0.830000,0.050000,0.640000,1.240000,1.710000,0.580000,1.150000,0.200000,0.000000
75%,2945.500000,32.000000,1977.000000,2.000000,20.500000,7.000000,2.000000,30.500000,62.500000,15.000000,37.000000,6.000000,107.000000,778.500000,601.000000,117.000000,38.000000,3.00000,15.000000,0.000000,0.150000,0.115000,4.000000,0.290000,1.785000,0.545000,6.010000,44.310000,36.300000,7.125000,2.525000,0.205000,1.190000,1.990000,3.770000,0.845000,2.420000,0.460000,0.000000
max,2986.000000,35.000000,3150.000000,9.000000,85.000000,36.000000,16.000000,97.000000,247.000000,64.000000,212.000000,27.000000,274.000000,2989.000000,2835.000000,526.000000,220.000000,14.00000,66.000000,75.000000,3.600000,6.000000,23.000000,6.000000,22.500000,11.250000,18.000000,151.000000,145.000000,27.680000,11.250000,6.000000,6.000000,7.200000,10.760000,3.750000,9.670000,11.250000,4.570000

In [28]:
#We can see that the 25% cutoff is 364
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 364].index)

In [29]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000,122.000000
mean,2900.991803,26.819672,1612.909836,1.729508,19.040984,6.270492,2.221311,26.631148,53.795082,12.590164,35.721311,5.819672,87.254098,704.500000,554.377049,105.754098,35.286885,2.696721,14.549180,4.901639,0.131311,0.096967,3.950820,0.228443,1.119098,0.374180,4.891557,38.493852,30.227377,5.821885,1.956803,0.145164,0.799836,1.448361,2.958033,0.660000,2.000984,0.339754,0.255410
std,47.694534,7.865624,734.293983,2.116589,17.595735,6.755514,2.972358,22.778198,53.090121,12.251331,36.109398,6.097034,56.827790,519.149181,479.331151,101.889286,48.609335,3.447096,14.141611,16.177430,0.160551,0.117311,4.431018,0.237282,0.895111,0.374022,2.093864,19.798463,19.580057,5.297185,2.357156,0.166566,0.657419,0.878843,2.591421,0.454611,1.773524,0.350642,0.796289
min,2824.000000,8.000000,368.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,5.000000,73.000000,45.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.290000,8.140000,5.590000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,0.000000,0.000000
25%,2857.250000,22.250000,946.500000,0.000000,7.000000,1.000000,0.000000,11.000000,15.000000,4.000000,10.000000,1.000000,42.250000,336.000000,230.000000,32.250000,2.250000,0.000000,4.000000,0.000000,0.000000,0.000000,1.000000,0.050000,0.475000,0.092500,3.875000,26.790000,18.040000,2.277500,0.155000,0.000000,0.235000,0.992500,0.870000,0.347500,0.720000,0.090000,0.000000
50%,2903.500000,30.000000,1648.500000,1.000000,13.000000,4.000000,1.000000,19.500000,33.000000,10.000000,24.000000,4.000000,84.000000,597.500000,440.500000,85.500000,14.000000,1.000000,10.000000,0.000000,0.100000,0.055000,2.000000,0.145000,0.820000,0.260000,4.995000,32.445000,24.055000,4.595000,0.870000,0.090000,0.700000,1.300000,2.200000,0.680000,1.420000,0.235000,0.000000
75%,2943.500000,33.000000,2235.500000,2.750000,25.000000,9.000000,4.000000,37.750000,77.000000,16.750000,52.750000,8.000000,121.750000,913.000000,690.000000,141.750000,46.750000,4.000000,22.000000,0.000000,0.187500,0.147500,5.000000,0.340000,1.797500,0.552500,5.940000,49.300000,40.225000,7.452500,2.830000,0.227500,1.162500,1.955000,4.102500,0.867500,2.760000,0.487500,0.000000
max,2983.000000,35.000000,3150.000000,9.000000,85.000000,36.000000,16.000000,97.000000,247.000000,64.000000,212.000000,27.000000,274.000000,2989.000000,2835.000000,526.000000,220.000000,14.000000,66.000000,75.000000,0.670000,0.560000,23.000000,1.010000,3.690000,1.590000,12.490000,117.560000,108.060000,27.680000,11.240000,0.630000,2.800000,4.540000,10.760000,1.980000,9.670000,1.900000,3.630000

In [30]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/PScomplete25.csv")