Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2defenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2defenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2defenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2defenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2forwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2forwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2forwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2forwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2goalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2goalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2goalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2goalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2goalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2midfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2midfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2midfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/ligue2/L2midfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name              0
Team              0
Tackles           0
Clearances        0
Interceptions     0
aerialsWon        0
Blocks            0
Mins              0
duelsWon          0
unnamed          52
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,0.0
mean,12.442308,32.076923,9.211538,14.134615,1.115385,725.673077,38.038462,NaN
std,9.183133,25.775689,7.341359,13.582037,1.450542,461.759878,27.115556,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,5.000000,12.500000,4.000000,3.000000,0.000000,270.000000,14.750000,NaN
50%,11.500000,25.500000,8.000000,11.000000,0.500000,796.000000,37.000000,NaN
75%,17.500000,49.250000,14.250000,19.250000,2.000000,1084.000000,54.250000,NaN
max,33.000000,110.000000,29.000000,60.000000,5.000000,1440.000000,115.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 2341)
dfDdef["ID"] = (dfDdef.index + 2341)
dfDatt["ID"] = (dfDatt.index + 2341)
dfDpas["ID"] = (dfDpas.index + 2341) #should end at id no 2392
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 2410
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 2426
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 2482
dfMdft.head(300) #to check final id number

             Name              Team  App  Mins    ID
0      T. Mangani           Ajaccio   15   247  2427
1       Y. M'Vila              Caen   12   877  2428
2       M. Autret              Caen    5    79  2429
3      M. Barreto             Dijon   14  1114  2430
4   T. Monconduit         Amiens SC   10   776  2431
5      C. Vincent            Bastia   14   794  2432
6       O. Orinel   Nîmes Olympique   10   665  2433
7    J. Eickmayer            Bastia   11   505  2434
8        M. López          Paris FC   14  1246  2435
9      Y. Demoncy          Guingamp   16  1269  2436
10   D. Louiserre          Guingamp   14  1207  2437
11       J. Benet  Grenoble Foot 38   15  1328  2438
12    A. Bobichon            Pau FC    2    32  2439
13   V. Marchetti          Paris FC   15  1083  2440
14     D. Tavares           Sochaux    1    20  2441
15      M. Cafaro          Paris FC   11   568  2442
16     A. Leautey         Amiens SC   16  1418  2443
17       L. Rajot              Caen   13   293  2444
18     J. Anziani            Pau FC   16  1355  2445
19    S. Beusnard            Pau FC   15  1094  2446
20     K. Kaiboue         Amiens SC   10   886  2447
21       V. Lobry         Amiens SC   15  1239  2448
22      K. Sidibé          Guingamp   12   944  2449
23        F. Tomi            Bastia    6   258  2450
24    G. Kyeremeh          Le Havre   12   706  2451
25     A. Boutrah            Bastia   16  1305  2452
26     T. Ducrocq            Bastia   14  1185  2453
27       A. Sagna          Guingamp    9   166  2454
28   A. Trouillet          Rodez AF   11   423  2455
29      M. Essimi     USL Dunkerque    5   136  2456
30      M. Bangré  Grenoble Foot 38   12   442  2457
31     E. Bardeli     USL Dunkerque   15  1126  2458
32     K. Gasnier            Pau FC    2    15  2459
33     K. Diawara          Le Havre   15   533  2460
34    F. Doucouré          Le Havre    9   609  2461
35   W. Younoussa          Rodez AF   16  1048  2462
36      I. Kebbal          Paris FC   13   910  2463
37      D. Gaucho              Caen   11   885  2464
38   S. Belloumou      Valenciennes   14  1087  2465
39      N. Kandil         Amiens SC   10   575  2466
40      L. Doucet     USL Dunkerque   16   281  2467
41        M. Achi          Rodez AF    9    57  2468
42      J. Janneh            Bastia   12   875  2469
43       R. Lutin         Amiens SC   16   660  2470
44        S. Diba  Grenoble Foot 38    5   261  2471
45      I. Fofana         Amiens SC   16   893  2472
46   J. N'Duquidi         Amiens SC    8   145  2473
47        K. Dong            Pau FC    4    26  2474
48      A. Ipiele      Valenciennes   16   866  2475
49  TAT. Averlant         Amiens SC    2   167  2476
50  RTR. Touzghar            Pau FC    2    18  2477
51      A. Camara          Paris FC   14   917  2478
52     A. Sekongo     USL Dunkerque   11   308  2479
53      M. Manitu         Amiens SC    9   128  2480
54   BMB. Merouga           Ajaccio    1     0  2481
55       IDI. Daf         Amiens SC    1    12  2482

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/ligue2/L2defender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/ligue2/L2forward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/ligue2/L2goalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/ligue2/L2midfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,R. Thomas,Valenciennes,7,213,2341,0,2.0,1,1,0.0,NaN,0.0,2,25,1,10,1,13,122,103,30,0,0,0,Defender,NaN
1,V. Sasso,USL Dunkerque,13,1160,2342,0,13.0,1,0,0.0,NaN,0.0,8,55,15,29,4,50,1118,1048,37,1,1,5,Defender,NaN
2,C. Junior Senneville,USL Dunkerque,1,28,2343,0,NaN,0,0,0.0,NaN,0.0,0,1,0,0,0,1,23,21,2,1,0,1,Defender,NaN
3,Abner,USL Dunkerque,15,1065,2344,2,3.0,0,0,0.0,NaN,0.0,13,25,11,8,1,55,529,461,38,27,2,8,Defender,NaN
4,G. Paquiez,Grenoble Foot 38,15,1308,2345,1,4.0,1,0,0.0,NaN,0.0,30,53,25,18,1,65,593,508,59,12,0,8,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,A. Camara,Paris FC,14,917,2478,0,8.0,3,1,0.0,NaN,0.0,32,10,11,15,2,83,511,443,43,7,1,10,Midfielder,NaN
138,A. Sekongo,USL Dunkerque,11,308,2479,1,11.0,2,0,0.0,NaN,0.0,1,3,3,4,3,13,127,107,7,3,2,4,Midfielder,NaN
139,M. Manitu,Amiens SC,9,128,2480,0,4.0,1,0,0.0,NaN,0.0,0,3,0,1,2,5,28,22,2,3,0,2,Midfielder,NaN
140,BMB. Merouga,Ajaccio,1,0,2481,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
141,IDI. Daf,Amiens SC,1,12,2482,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,7,5,2,0,0,0,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,R. Thomas,Valenciennes,7,213,2341,0,2.0,1,1,0.0,0.0,0.0,2,25,1,10,1,13,122,103,30,0,0,0,Defender,0.0
1,V. Sasso,USL Dunkerque,13,1160,2342,0,13.0,1,0,0.0,0.0,0.0,8,55,15,29,4,50,1118,1048,37,1,1,5,Defender,0.0
2,C. Junior Senneville,USL Dunkerque,1,28,2343,0,0.0,0,0,0.0,0.0,0.0,0,1,0,0,0,1,23,21,2,1,0,1,Defender,0.0
3,Abner,USL Dunkerque,15,1065,2344,2,3.0,0,0,0.0,0.0,0.0,13,25,11,8,1,55,529,461,38,27,2,8,Defender,0.0
4,G. Paquiez,Grenoble Foot 38,15,1308,2345,1,4.0,1,0,0.0,0.0,0.0,30,53,25,18,1,65,593,508,59,12,0,8,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,J. N'Duquidi,Amiens SC,8,145,2473,0,1.0,0,0,0.0,0.0,0.0,1,2,1,5,1,8,72,62,4,0,0,0,Midfielder,0.0
133,K. Dong,Pau FC,4,26,2474,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,1,11,9,2,1,0,1,Midfielder,0.0
134,A. Ipiele,Valenciennes,16,866,2475,3,20.0,4,2,0.0,0.0,0.0,9,5,7,17,7,55,276,185,10,41,1,17,Midfielder,0.0
135,TAT. Averlant,Amiens SC,2,167,2476,1,3.0,3,1,0.0,0.0,0.0,3,0,0,1,0,10,31,27,4,5,1,1,Midfielder,0.0
136,RTR. Touzghar,Pau FC,2,18,2477,0,1.0,0,0,0.0,0.0,0.0,0,0,1,2,0,2,7,4,0,1,0,0,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,2341,Defender,R. Thomas,Valenciennes,7,213,0,2.0,1,1,0.0,0.0,0.0,2,25,1,10,1,13,122,103,30,0,0,0,0.0
1,2342,Defender,V. Sasso,USL Dunkerque,13,1160,0,13.0,1,0,0.0,0.0,0.0,8,55,15,29,4,50,1118,1048,37,1,1,5,0.0
2,2343,Defender,C. Junior Senneville,USL Dunkerque,1,28,0,0.0,0,0,0.0,0.0,0.0,0,1,0,0,0,1,23,21,2,1,0,1,0.0
3,2344,Defender,Abner,USL Dunkerque,15,1065,2,3.0,0,0,0.0,0.0,0.0,13,25,11,8,1,55,529,461,38,27,2,8,0.0
4,2345,Defender,G. Paquiez,Grenoble Foot 38,15,1308,1,4.0,1,0,0.0,0.0,0.0,30,53,25,18,1,65,593,508,59,12,0,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,2473,Midfielder,J. N'Duquidi,Amiens SC,8,145,0,1.0,0,0,0.0,0.0,0.0,1,2,1,5,1,8,72,62,4,0,0,0,0.0
133,2474,Midfielder,K. Dong,Pau FC,4,26,0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,1,11,9,2,1,0,1,0.0
134,2475,Midfielder,A. Ipiele,Valenciennes,16,866,3,20.0,4,2,0.0,0.0,0.0,9,5,7,17,7,55,276,185,10,41,1,17,0.0
135,2476,Midfielder,TAT. Averlant,Amiens SC,2,167,1,3.0,3,1,0.0,0.0,0.0,3,0,0,1,0,10,31,27,4,5,1,1,0.0
136,2477,Midfielder,RTR. Touzghar,Pau FC,2,18,0,1.0,0,0,0.0,0.0,0.0,0,0,1,2,0,2,7,4,0,1,0,0,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.0,142.0,142.0,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000
mean,2411.500000,11.253521,657.859155,0.640845,6.985915,2.450704,0.767606,0.0,0.0,0.0,10.380282,16.598592,6.176056,9.697183,1.922535,32.161972,305.802817,253.098592,42.190141,12.725352,1.035211,6.091549,2.105634
std,41.135953,4.733218,468.002994,1.175045,7.961776,3.369823,1.345681,0.0,0.0,0.0,9.890702,20.682696,6.593893,11.677699,2.708206,27.428990,271.175828,237.834059,54.084637,20.528529,1.630437,7.428052,8.863590
min,2341.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2376.250000,9.000000,196.250000,0.000000,1.000000,0.000000,0.000000,0.0,0.0,0.0,1.000000,2.000000,0.250000,1.250000,0.000000,7.250000,73.000000,62.750000,4.250000,0.000000,0.000000,0.000000,0.000000
50%,2411.500000,13.000000,693.500000,0.000000,4.500000,1.000000,0.000000,0.0,0.0,0.0,8.000000,8.000000,4.000000,5.000000,1.000000,25.000000,250.000000,188.500000,25.500000,3.000000,0.000000,3.000000,0.000000
75%,2446.750000,15.000000,1065.750000,1.000000,11.750000,4.000000,1.000000,0.0,0.0,0.0,17.000000,23.750000,10.000000,14.000000,3.000000,53.750000,493.500000,404.000000,60.750000,15.750000,2.000000,9.000000,0.000000
max,2482.000000,16.000000,1440.000000,6.000000,38.000000,15.000000,9.000000,0.0,0.0,0.0,40.000000,110.000000,29.000000,60.000000,15.000000,115.000000,1273.000000,1135.000000,289.000000,115.000000,7.000000,35.000000,67.000000

There are no expected stats captured within this dataset, so we remove them

In [16]:
finalData = finalData.drop(columns=["xG", "npxG", "xA"])

Adding additional data fields

In [17]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90


finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,2341,Defender,R. Thomas,Valenciennes,7,213,0,2.0,1,1,2,25,1,10,1,13,122,103,30,0,0,0,0.0,0.422535,0.000000,1,0.422535,0.845070,0.422535,5.492958,51.549296,43.521127,12.676056,0.000000,0.000000,0.000000,0.845070,10.563380,0.422535,4.225352,0.422535,0.0
1,2342,Defender,V. Sasso,USL Dunkerque,13,1160,0,13.0,1,0,8,55,15,29,4,50,1118,1048,37,1,1,5,0.0,0.000000,0.000000,0,0.000000,1.008621,0.077586,3.879310,86.741379,81.310345,2.870690,0.077586,0.077586,0.387931,0.620690,4.267241,1.163793,2.250000,0.310345,0.0
2,2343,Defender,C. Junior Senneville,USL Dunkerque,1,28,0,0.0,0,0,0,1,0,0,0,1,23,21,2,1,0,1,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,3.214286,73.928571,67.500000,6.428571,3.214286,0.000000,3.214286,0.000000,3.214286,0.000000,0.000000,0.000000,0.0
3,2344,Defender,Abner,USL Dunkerque,15,1065,2,3.0,0,0,13,25,11,8,1,55,529,461,38,27,2,8,0.0,0.000000,0.169014,2,0.169014,0.253521,0.000000,4.647887,44.704225,38.957746,3.211268,2.281690,0.169014,0.676056,1.098592,2.112676,0.929577,0.676056,0.084507,0.0
4,2345,Defender,G. Paquiez,Grenoble Foot 38,15,1308,1,4.0,1,0,30,53,25,18,1,65,593,508,59,12,0,8,0.0,0.000000,0.068807,1,0.068807,0.275229,0.068807,4.472477,40.802752,34.954128,4.059633,0.825688,0.000000,0.550459,2.064220,3.646789,1.720183,1.238532,0.068807,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,2473,Midfielder,J. N'Duquidi,Amiens SC,8,145,0,1.0,0,0,1,2,1,5,1,8,72,62,4,0,0,0,0.0,0.000000,0.000000,0,0.000000,0.620690,0.000000,4.965517,44.689655,38.482759,2.482759,0.000000,0.000000,0.000000,0.620690,1.241379,0.620690,3.103448,0.620690,0.0
133,2474,Midfielder,K. Dong,Pau FC,4,26,0,0.0,0,0,0,0,0,0,0,1,11,9,2,1,0,1,0.0,0.000000,0.000000,0,0.000000,0.000000,0.000000,3.461538,38.076923,31.153846,6.923077,3.461538,0.000000,3.461538,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
134,2475,Midfielder,A. Ipiele,Valenciennes,16,866,3,20.0,4,2,9,5,7,17,7,55,276,185,10,41,1,17,0.0,0.207852,0.311778,5,0.519630,2.078522,0.415704,5.715935,28.683603,19.226328,1.039261,4.260970,0.103926,1.766744,0.935335,0.519630,0.727483,1.766744,0.727483,0.0
135,2476,Midfielder,TAT. Averlant,Amiens SC,2,167,1,3.0,3,1,3,0,0,1,0,10,31,27,4,5,1,1,0.0,0.538922,0.538922,2,1.077844,1.616766,1.616766,5.389222,16.706587,14.550898,2.155689,2.694611,0.538922,0.538922,1.616766,0.000000,0.000000,0.538922,0.000000,0.0
136,2477,Midfielder,RTR. Touzghar,Pau FC,2,18,0,1.0,0,0,0,0,1,2,0,2,7,4,0,1,0,0,0.0,0.000000,0.000000,0,0.000000,5.000000,0.000000,10.000000,35.000000,20.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,5.000000,10.000000,0.000000,0.0

Removing NaN again and fixing decimal places

In [18]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,2341,Defender,R. Thomas,Valenciennes,7,213,0,2.0,1,1,2,25,1,10,1,13,122,103,30,0,0,0,0.0,0.42,0.00,1,0.42,0.85,0.42,5.49,51.55,43.52,12.68,0.00,0.00,0.00,0.85,10.56,0.42,4.23,0.42,0.0
1,2342,Defender,V. Sasso,USL Dunkerque,13,1160,0,13.0,1,0,8,55,15,29,4,50,1118,1048,37,1,1,5,0.0,0.00,0.00,0,0.00,1.01,0.08,3.88,86.74,81.31,2.87,0.08,0.08,0.39,0.62,4.27,1.16,2.25,0.31,0.0
2,2343,Defender,C. Junior Senneville,USL Dunkerque,1,28,0,0.0,0,0,0,1,0,0,0,1,23,21,2,1,0,1,0.0,0.00,0.00,0,0.00,0.00,0.00,3.21,73.93,67.50,6.43,3.21,0.00,3.21,0.00,3.21,0.00,0.00,0.00,0.0
3,2344,Defender,Abner,USL Dunkerque,15,1065,2,3.0,0,0,13,25,11,8,1,55,529,461,38,27,2,8,0.0,0.00,0.17,2,0.17,0.25,0.00,4.65,44.70,38.96,3.21,2.28,0.17,0.68,1.10,2.11,0.93,0.68,0.08,0.0
4,2345,Defender,G. Paquiez,Grenoble Foot 38,15,1308,1,4.0,1,0,30,53,25,18,1,65,593,508,59,12,0,8,0.0,0.00,0.07,1,0.07,0.28,0.07,4.47,40.80,34.95,4.06,0.83,0.00,0.55,2.06,3.65,1.72,1.24,0.07,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,2473,Midfielder,J. N'Duquidi,Amiens SC,8,145,0,1.0,0,0,1,2,1,5,1,8,72,62,4,0,0,0,0.0,0.00,0.00,0,0.00,0.62,0.00,4.97,44.69,38.48,2.48,0.00,0.00,0.00,0.62,1.24,0.62,3.10,0.62,0.0
133,2474,Midfielder,K. Dong,Pau FC,4,26,0,0.0,0,0,0,0,0,0,0,1,11,9,2,1,0,1,0.0,0.00,0.00,0,0.00,0.00,0.00,3.46,38.08,31.15,6.92,3.46,0.00,3.46,0.00,0.00,0.00,0.00,0.00,0.0
134,2475,Midfielder,A. Ipiele,Valenciennes,16,866,3,20.0,4,2,9,5,7,17,7,55,276,185,10,41,1,17,0.0,0.21,0.31,5,0.52,2.08,0.42,5.72,28.68,19.23,1.04,4.26,0.10,1.77,0.94,0.52,0.73,1.77,0.73,0.0
135,2476,Midfielder,TAT. Averlant,Amiens SC,2,167,1,3.0,3,1,3,0,0,1,0,10,31,27,4,5,1,1,0.0,0.54,0.54,2,1.08,1.62,1.62,5.39,16.71,14.55,2.16,2.69,0.54,0.54,1.62,0.00,0.00,0.54,0.00,0.0
136,2477,Midfielder,RTR. Touzghar,Pau FC,2,18,0,1.0,0,0,0,0,1,2,0,2,7,4,0,1,0,0,0.0,0.00,0.00,0,0.00,5.00,0.00,10.00,35.00,20.00,0.00,5.00,0.00,0.00,0.00,0.00,5.00,10.00,0.00,0.0

Adding and moving "League" column

In [19]:
#label
leagueLabel = "Ligue 2"

#adding label to df
finalData["League"] = leagueLabel

In [20]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,2341,Defender,Ligue 2,R. Thomas,Valenciennes,7,213,0,2.0,1,1,2,25,1,10,1,13,122,103,30,0,0,0,0.0,0.42,0.00,1,0.42,0.85,0.42,5.49,51.55,43.52,12.68,0.00,0.00,0.00,0.85,10.56,0.42,4.23,0.42,0.0
1,2342,Defender,Ligue 2,V. Sasso,USL Dunkerque,13,1160,0,13.0,1,0,8,55,15,29,4,50,1118,1048,37,1,1,5,0.0,0.00,0.00,0,0.00,1.01,0.08,3.88,86.74,81.31,2.87,0.08,0.08,0.39,0.62,4.27,1.16,2.25,0.31,0.0
2,2343,Defender,Ligue 2,C. Junior Senneville,USL Dunkerque,1,28,0,0.0,0,0,0,1,0,0,0,1,23,21,2,1,0,1,0.0,0.00,0.00,0,0.00,0.00,0.00,3.21,73.93,67.50,6.43,3.21,0.00,3.21,0.00,3.21,0.00,0.00,0.00,0.0
3,2344,Defender,Ligue 2,Abner,USL Dunkerque,15,1065,2,3.0,0,0,13,25,11,8,1,55,529,461,38,27,2,8,0.0,0.00,0.17,2,0.17,0.25,0.00,4.65,44.70,38.96,3.21,2.28,0.17,0.68,1.10,2.11,0.93,0.68,0.08,0.0
4,2345,Defender,Ligue 2,G. Paquiez,Grenoble Foot 38,15,1308,1,4.0,1,0,30,53,25,18,1,65,593,508,59,12,0,8,0.0,0.00,0.07,1,0.07,0.28,0.07,4.47,40.80,34.95,4.06,0.83,0.00,0.55,2.06,3.65,1.72,1.24,0.07,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,2473,Midfielder,Ligue 2,J. N'Duquidi,Amiens SC,8,145,0,1.0,0,0,1,2,1,5,1,8,72,62,4,0,0,0,0.0,0.00,0.00,0,0.00,0.62,0.00,4.97,44.69,38.48,2.48,0.00,0.00,0.00,0.62,1.24,0.62,3.10,0.62,0.0
133,2474,Midfielder,Ligue 2,K. Dong,Pau FC,4,26,0,0.0,0,0,0,0,0,0,0,1,11,9,2,1,0,1,0.0,0.00,0.00,0,0.00,0.00,0.00,3.46,38.08,31.15,6.92,3.46,0.00,3.46,0.00,0.00,0.00,0.00,0.00,0.0
134,2475,Midfielder,Ligue 2,A. Ipiele,Valenciennes,16,866,3,20.0,4,2,9,5,7,17,7,55,276,185,10,41,1,17,0.0,0.21,0.31,5,0.52,2.08,0.42,5.72,28.68,19.23,1.04,4.26,0.10,1.77,0.94,0.52,0.73,1.77,0.73,0.0
135,2476,Midfielder,Ligue 2,TAT. Averlant,Amiens SC,2,167,1,3.0,3,1,3,0,0,1,0,10,31,27,4,5,1,1,0.0,0.54,0.54,2,1.08,1.62,1.62,5.39,16.71,14.55,2.16,2.69,0.54,0.54,1.62,0.00,0.00,0.54,0.00,0.0
136,2477,Midfielder,Ligue 2,RTR. Touzghar,Pau FC,2,18,0,1.0,0,0,0,0,1,2,0,2,7,4,0,1,0,0,0.0,0.00,0.00,0,0.00,5.00,0.00,10.00,35.00,20.00,0.00,5.00,0.00,0.00,0.00,0.00,5.00,10.00,0.00,0.0

In [21]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/L2complete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [22]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [23]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [24]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.00000,120.000000,120.000000,120.000000,120.000000
mean,2410.308333,12.725000,774.241667,0.758333,8.183333,2.883333,0.908333,12.225000,19.600000,7.258333,11.366667,2.258333,37.800000,359.833333,297.875000,49.650000,14.683333,1.216667,7.050000,2.491667,0.123667,0.082333,1.666667,0.206167,1.015250,0.374500,4.409917,39.838917,32.925917,5.277500,1.680750,0.139917,0.814917,1.454583,2.26875,0.824750,1.323833,0.267417,0.325083
std,40.285493,3.266747,413.805703,1.243442,8.106418,3.493531,1.420119,9.677543,21.170139,6.614849,11.969101,2.817997,26.150373,260.930762,232.261826,55.700678,21.726715,1.710980,7.674962,9.597790,0.201511,0.134031,2.224135,0.277244,0.892915,0.425956,1.943828,15.416956,14.725536,4.058331,2.030441,0.210284,0.779928,0.981069,2.08151,0.590164,1.132468,0.310463,1.075508
min,2341.000000,2.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.490000,9.520000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,2375.750000,11.000000,360.250000,0.000000,2.000000,0.000000,0.000000,4.000000,5.000000,2.000000,3.000000,0.000000,14.000000,130.750000,106.500000,10.750000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.315000,0.000000,3.355000,28.432500,20.890000,2.420000,0.000000,0.000000,0.130000,0.857500,0.72000,0.337500,0.477500,0.000000,0.000000
50%,2408.000000,14.000000,843.500000,0.000000,6.000000,1.500000,0.000000,11.000000,10.500000,5.000000,7.000000,1.000000,37.500000,337.500000,260.500000,36.000000,5.500000,0.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.100000,0.810000,0.220000,4.625000,38.940000,32.000000,4.520000,0.855000,0.000000,0.710000,1.435000,1.53000,0.825000,1.035000,0.145000,0.000000
75%,2446.250000,15.000000,1117.000000,1.000000,12.000000,4.000000,1.000000,19.000000,26.000000,11.000000,15.500000,3.000000,55.000000,515.500000,429.000000,64.000000,20.500000,2.000000,10.000000,0.000000,0.155000,0.140000,2.250000,0.322500,1.630000,0.542500,5.505000,49.335000,41.625000,6.955000,2.667500,0.270000,1.180000,1.952500,3.33500,1.220000,1.805000,0.452500,0.000000
max,2480.000000,16.000000,1440.000000,6.000000,38.000000,15.000000,9.000000,40.000000,110.000000,29.000000,60.000000,15.000000,115.000000,1273.000000,1135.000000,289.000000,115.000000,7.000000,35.000000,67.000000,1.050000,0.590000,12.000000,1.240000,3.210000,1.740000,8.210000,91.950000,81.980000,19.270000,10.550000,1.440000,3.600000,4.310000,10.56000,2.700000,4.890000,1.410000,6.000000

In [25]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/L2complete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [26]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [27]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000
mean,2411.500000,11.253521,657.859155,0.640845,6.985915,2.450704,0.767606,10.380282,16.598592,6.176056,9.697183,1.922535,32.161972,305.802817,253.098592,42.190141,12.725352,1.035211,6.091549,2.105634,0.104507,0.069577,1.408451,0.174225,1.037817,0.342324,4.215423,37.265352,30.719718,4.939366,2.038873,0.131197,0.968732,1.356408,2.023662,0.793732,1.326479,0.245141,0.274718
std,41.135953,4.733218,468.002994,1.175045,7.961776,3.369823,1.345681,9.890702,20.682696,6.593893,11.677699,2.708206,27.428990,271.175828,237.834059,54.084637,20.528529,1.630437,7.428052,8.863590,0.190492,0.126709,2.131010,0.265472,1.072456,0.499998,2.332055,18.215120,16.505620,4.218600,3.105870,0.246287,1.455486,1.374781,2.143025,0.828733,1.406063,0.329562,0.995073
min,2341.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2376.250000,9.000000,196.250000,0.000000,1.000000,0.000000,0.000000,1.000000,2.000000,0.250000,1.250000,0.000000,7.250000,73.000000,62.750000,4.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.212500,0.000000,3.200000,25.490000,18.962500,1.825000,0.000000,0.000000,0.000000,0.350000,0.525000,0.020000,0.312500,0.000000,0.000000
50%,2411.500000,13.000000,693.500000,0.000000,4.500000,1.000000,0.000000,8.000000,8.000000,4.000000,5.000000,1.000000,25.000000,250.000000,188.500000,25.500000,3.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.500000,0.030000,0.800000,0.150000,4.530000,37.105000,31.170000,4.185000,0.815000,0.000000,0.640000,1.200000,1.240000,0.700000,0.955000,0.100000,0.000000
75%,2446.750000,15.000000,1065.750000,1.000000,11.750000,4.000000,1.000000,17.000000,23.750000,10.000000,14.000000,3.000000,53.750000,493.500000,404.000000,60.750000,15.750000,2.000000,9.000000,0.000000,0.117500,0.100000,2.000000,0.287500,1.650000,0.460000,5.535000,49.280000,41.425000,6.902500,2.830000,0.217500,1.255000,1.875000,3.112500,1.160000,1.815000,0.395000,0.000000
max,2482.000000,16.000000,1440.000000,6.000000,38.000000,15.000000,9.000000,40.000000,110.000000,29.000000,60.000000,15.000000,115.000000,1273.000000,1135.000000,289.000000,115.000000,7.000000,35.000000,67.000000,1.050000,0.590000,12.000000,1.240000,6.000000,3.670000,12.000000,91.950000,81.980000,19.270000,22.040000,1.840000,11.250000,12.000000,10.560000,5.000000,10.000000,1.580000,6.000000

In [28]:
#We can see that the 25% cutoff is 196.25, so we round down to 196
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 196].index)

In [29]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000,106.000000
mean,2408.254717,13.188679,858.424528,0.849057,9.066038,3.169811,1.000000,13.584906,21.716981,8.094340,12.632075,2.509434,42.018868,401.415094,332.339623,55.452830,16.301887,1.349057,7.896226,2.594340,0.123585,0.088113,1.849057,0.211887,1.030943,0.369717,4.525755,41.403868,34.275377,5.454245,1.693302,0.139717,0.863962,1.507736,2.280849,0.856321,1.354717,0.272358,0.198208
std,40.542761,2.794938,364.113534,1.293150,8.212962,3.608117,1.480026,9.451498,21.586043,6.582123,12.171258,2.899081,24.865727,249.206736,225.347304,56.753961,22.605591,1.767659,7.766754,10.139765,0.195902,0.132256,2.296135,0.268945,0.892583,0.416574,1.824167,15.265177,14.723303,4.056855,2.019362,0.173943,0.738595,0.928561,1.999788,0.543564,1.150335,0.293931,0.731382
min,2341.000000,5.000000,197.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,59.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.120000,14.490000,9.520000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2372.250000,11.000000,569.750000,0.000000,2.250000,0.250000,0.000000,5.000000,6.000000,3.000000,4.000000,0.000000,19.250000,211.000000,166.500000,22.250000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.322500,0.015000,3.452500,31.602500,24.862500,2.872500,0.080000,0.000000,0.250000,0.917500,0.775000,0.427500,0.497500,0.000000,0.000000
50%,2404.500000,14.000000,894.000000,0.000000,7.000000,2.000000,0.000000,12.000000,13.500000,6.000000,9.000000,1.500000,41.500000,366.500000,282.500000,39.500000,6.000000,0.000000,6.000000,0.000000,0.000000,0.000000,1.000000,0.110000,0.830000,0.220000,4.625000,39.285000,32.880000,4.660000,0.950000,0.000000,0.780000,1.440000,1.540000,0.880000,1.035000,0.195000,0.000000
75%,2444.750000,15.000000,1155.250000,1.000000,13.000000,4.750000,1.000000,19.750000,27.750000,12.000000,18.000000,4.000000,59.750000,528.500000,448.250000,69.250000,27.000000,2.000000,11.000000,0.000000,0.165000,0.140000,3.000000,0.327500,1.635000,0.507500,5.572500,50.202500,43.310000,7.060000,2.645000,0.270000,1.255000,1.935000,3.345000,1.220000,1.815000,0.445000,0.000000
max,2479.000000,16.000000,1440.000000,6.000000,38.000000,15.000000,9.000000,40.000000,110.000000,29.000000,60.000000,15.000000,115.000000,1273.000000,1135.000000,289.000000,115.000000,7.000000,35.000000,67.000000,1.050000,0.590000,12.000000,1.240000,3.210000,1.740000,8.210000,91.950000,81.980000,19.270000,10.550000,0.630000,3.140000,4.310000,10.560000,2.550000,4.890000,1.030000,4.470000

In [30]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/L2complete25.csv")