Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2defenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2defenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2defenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2defenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2forwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2forwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2forwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2forwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2goalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2goalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2goalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2goalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2goalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2midfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2midfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2midfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/laliga2/LALIGA2midfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name              0
Team              0
Tackles           0
Clearances        0
Interceptions     0
aerialsWon        0
Blocks            0
Mins              0
duelsWon          0
unnamed          83
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,0.0
mean,32.397590,76.421687,20.253012,31.265060,2.216867,1722.807229,84.819277,NaN
std,23.630251,58.498097,12.921756,26.993262,2.083900,1010.869638,55.085774,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,15.000000,34.500000,10.000000,12.000000,1.000000,1093.000000,44.500000,NaN
50%,29.000000,65.000000,19.000000,26.000000,2.000000,1676.000000,86.000000,NaN
75%,42.500000,108.500000,29.000000,45.500000,3.000000,2360.000000,113.000000,NaN
max,115.000000,270.000000,47.000000,130.000000,8.000000,3957.000000,234.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 1478)
dfDdef["ID"] = (dfDdef.index + 1478)
dfDatt["ID"] = (dfDatt.index + 1478)
dfDpas["ID"] = (dfDpas.index + 1478) #should end at id no 1560
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 1606
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 1630
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 1714
dfMdft.head(300) #to check final id number

                Name          Team  App  Mins    ID
0         S. Cazorla   Real Oviedo   37  2112  1631
1          L. Júnior       CD Lugo   43   492  1632
2            A. Sanz   CD Tenerife   19  1301  1633
3        F. Portillo        Huesca   30  1055  1634
4         S. Álvarez         Eibar   41  2793  1635
..               ...           ...  ...   ...   ...
79     NTN. Tounkara   AD Alcorcón    6    16  1710
80  DTD. Tejón Naves   Real Oviedo    1     0  1711
81        LRL. Rubio  FC Cartagena    7     0  1712
82        ROR. Ojeda        Huesca    2    16  1713
83      MDM. Delgado         Eibar    1     0  1714

[84 rows x 5 columns]

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/laliga2/LALIGA2defender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/laliga2/LALIGA2forward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/laliga2/LALIGA2goalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/laliga2/LALIGA2midfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,J. Ángel,Sporting Gijón,38,1380,1478,2,13.0,3,1,0.0,NaN,0.0,26,44,10,25,2,66,685,552,113,155,4,27,Defender,NaN
1,J. Pulido,Huesca,37,3184,1479,1,20.0,7,2,0.0,NaN,0.0,29,231,40,79,2,132,1579,1395,167,2,3,12,Defender,NaN
2,M. Mateu,CD Tenerife,37,3218,1480,5,24.0,7,2,0.0,NaN,0.0,36,83,23,12,5,91,1313,974,340,272,9,57,Defender,NaN
3,N. Maraš,Mirandés,35,2026,1481,1,11.0,2,0,0.0,NaN,0.0,30,124,17,66,1,108,982,828,120,2,2,9,Defender,NaN
4,A. Arbilla,Eibar,30,2326,1482,0,17.0,5,0,0.0,NaN,0.0,23,139,36,42,3,80,1703,1424,356,1,0,6,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,NTN. Tounkara,AD Alcorcón,6,16,1710,0,NaN,0,0,0.0,NaN,0.0,1,0,1,0,0,1,6,5,1,0,0,0,Midfielder,NaN
233,DTD. Tejón Naves,Real Oviedo,1,0,1711,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
234,LRL. Rubio,FC Cartagena,7,0,1712,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN
235,ROR. Ojeda,Huesca,2,16,1713,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,2,2,1,0,0,0,0,Midfielder,NaN
236,MDM. Delgado,Eibar,1,0,1714,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,0,0,0,0,0,0,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,J. Ángel,Sporting Gijón,38,1380,1478,2,13.0,3,1,0.0,0.0,0.0,26,44,10,25,2,66,685,552,113,155,4,27,Defender,0.0
1,J. Pulido,Huesca,37,3184,1479,1,20.0,7,2,0.0,0.0,0.0,29,231,40,79,2,132,1579,1395,167,2,3,12,Defender,0.0
2,M. Mateu,CD Tenerife,37,3218,1480,5,24.0,7,2,0.0,0.0,0.0,36,83,23,12,5,91,1313,974,340,272,9,57,Defender,0.0
3,N. Maraš,Mirandés,35,2026,1481,1,11.0,2,0,0.0,0.0,0.0,30,124,17,66,1,108,982,828,120,2,2,9,Defender,0.0
4,A. Arbilla,Eibar,30,2326,1482,0,17.0,5,0,0.0,0.0,0.0,23,139,36,42,3,80,1703,1424,356,1,0,6,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,A. Madariaga,Eibar,29,1405,1705,0,28.0,12,3,0.0,0.0,0.0,25,20,17,26,4,86,609,486,33,14,2,13,Midfielder,0.0
228,M. Cantero,Burgos Club de Fútbol,25,320,1706,0,2.0,0,0,0.0,0.0,0.0,4,6,0,7,2,12,149,120,7,3,0,2,Midfielder,0.0
229,A. Ochoa,Málaga,32,1024,1707,0,12.0,5,0,0.0,0.0,0.0,18,4,3,3,3,65,401,312,48,17,2,16,Midfielder,0.0
230,A. Martín,Mirandés,36,1642,1708,1,23.0,6,2,0.0,0.0,0.0,30,17,15,24,4,91,575,451,68,18,2,14,Midfielder,0.0
231,DFD. Fernández,CD Tenerife,15,316,1709,0,6.0,1,1,0.0,0.0,0.0,8,0,1,4,3,27,76,55,3,4,0,2,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,1478,Defender,J. Ángel,Sporting Gijón,38,1380,2,13.0,3,1,0.0,0.0,0.0,26,44,10,25,2,66,685,552,113,155,4,27,0.0
1,1479,Defender,J. Pulido,Huesca,37,3184,1,20.0,7,2,0.0,0.0,0.0,29,231,40,79,2,132,1579,1395,167,2,3,12,0.0
2,1480,Defender,M. Mateu,CD Tenerife,37,3218,5,24.0,7,2,0.0,0.0,0.0,36,83,23,12,5,91,1313,974,340,272,9,57,0.0
3,1481,Defender,N. Maraš,Mirandés,35,2026,1,11.0,2,0,0.0,0.0,0.0,30,124,17,66,1,108,982,828,120,2,2,9,0.0
4,1482,Defender,A. Arbilla,Eibar,30,2326,0,17.0,5,0,0.0,0.0,0.0,23,139,36,42,3,80,1703,1424,356,1,0,6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,1705,Midfielder,A. Madariaga,Eibar,29,1405,0,28.0,12,3,0.0,0.0,0.0,25,20,17,26,4,86,609,486,33,14,2,13,0.0
228,1706,Midfielder,M. Cantero,Burgos Club de Fútbol,25,320,0,2.0,0,0,0.0,0.0,0.0,4,6,0,7,2,12,149,120,7,3,0,2,0.0
229,1707,Midfielder,A. Ochoa,Málaga,32,1024,0,12.0,5,0,0.0,0.0,0.0,18,4,3,3,3,65,401,312,48,17,2,16,0.0
230,1708,Midfielder,A. Martín,Mirandés,36,1642,1,23.0,6,2,0.0,0.0,0.0,30,17,15,24,4,91,575,451,68,18,2,14,0.0
231,1709,Midfielder,DFD. Fernández,CD Tenerife,15,316,0,6.0,1,1,0.0,0.0,0.0,8,0,1,4,3,27,76,55,3,4,0,2,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.0,237.0,237.0,237.000000,237.00000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000
mean,1596.000000,29.354430,1426.472574,1.004219,15.489451,5.063291,1.518987,0.0,0.0,0.0,23.468354,37.21097,12.582278,23.008439,3.848101,70.257384,571.388186,451.679325,90.573840,25.814346,1.696203,11.704641,4.552743
std,68.560193,13.147183,1079.363790,1.530752,18.732192,6.954468,2.453953,0.0,0.0,0.0,23.198390,47.99565,13.224535,27.486976,5.099240,60.256349,500.834077,415.876212,134.040595,42.320700,2.482248,13.857221,20.877629
min,1478.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1537.000000,19.000000,514.000000,0.000000,2.000000,0.000000,0.000000,0.0,0.0,0.0,4.000000,5.00000,1.000000,3.000000,0.000000,17.000000,149.000000,119.000000,13.000000,0.000000,0.000000,1.000000,0.000000
50%,1596.000000,35.000000,1331.000000,0.000000,9.000000,2.000000,0.000000,0.0,0.0,0.0,18.000000,18.00000,8.000000,14.000000,2.000000,61.000000,457.000000,352.000000,49.000000,5.000000,1.000000,7.000000,0.000000
75%,1655.000000,39.000000,2326.000000,1.000000,21.000000,7.000000,2.000000,0.0,0.0,0.0,36.000000,52.00000,21.000000,32.000000,5.000000,109.000000,908.000000,677.000000,113.000000,36.000000,2.000000,17.000000,0.000000
max,1714.000000,45.000000,3978.000000,7.000000,103.000000,36.000000,13.000000,0.0,0.0,0.0,115.000000,270.00000,61.000000,176.000000,25.000000,242.000000,2580.000000,2220.000000,752.000000,272.000000,14.000000,76.000000,146.000000

There are no expected stats captured within this dataset, so we remove them

In [16]:
finalData = finalData.drop(columns=["xG", "npxG", "xA"])

Adding additional data fields

In [17]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90


finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,1478,Defender,J. Ángel,Sporting Gijón,38,1380,2,13.0,3,1,26,44,10,25,2,66,685,552,113,155,4,27,0.0,0.065217,0.130435,3,0.195652,0.847826,0.195652,4.304348,44.673913,36.000000,7.369565,10.108696,0.260870,1.760870,1.695652,2.869565,0.652174,1.630435,0.130435,0.0
1,1479,Defender,J. Pulido,Huesca,37,3184,1,20.0,7,2,29,231,40,79,2,132,1579,1395,167,2,3,12,0.0,0.056533,0.028266,3,0.084799,0.565327,0.197864,3.731156,44.632538,39.431533,4.720477,0.056533,0.084799,0.339196,0.819724,6.529523,1.130653,2.233040,0.056533,0.0
2,1480,Defender,M. Mateu,CD Tenerife,37,3218,5,24.0,7,2,36,83,23,12,5,91,1313,974,340,272,9,57,0.0,0.055935,0.139838,7,0.195774,0.671224,0.195774,2.545059,36.721566,27.240522,9.509012,7.607209,0.251709,1.594158,1.006837,2.321318,0.643257,0.335612,0.139838,0.0
3,1481,Defender,N. Maraš,Mirandés,35,2026,1,11.0,2,0,30,124,17,66,1,108,982,828,120,2,2,9,0.0,0.000000,0.044423,1,0.044423,0.488648,0.088845,4.797631,43.622902,36.781836,5.330701,0.088845,0.088845,0.399803,1.332675,5.508391,0.755183,2.931885,0.044423,0.0
4,1482,Defender,A. Arbilla,Eibar,30,2326,0,17.0,5,0,23,139,36,42,3,80,1703,1424,356,1,0,6,0.0,0.000000,0.000000,0,0.000000,0.657782,0.193465,3.095443,65.894239,55.098882,13.774721,0.038693,0.000000,0.232158,0.889940,5.378332,1.392949,1.625107,0.116079,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,1705,Midfielder,A. Madariaga,Eibar,29,1405,0,28.0,12,3,25,20,17,26,4,86,609,486,33,14,2,13,0.0,0.192171,0.000000,3,0.192171,1.793594,0.768683,5.508897,39.010676,31.131673,2.113879,0.896797,0.128114,0.832740,1.601423,1.281139,1.088968,1.665480,0.256228,0.0
228,1706,Midfielder,M. Cantero,Burgos Club de Fútbol,25,320,0,2.0,0,0,4,6,0,7,2,12,149,120,7,3,0,2,0.0,0.000000,0.000000,0,0.000000,0.562500,0.000000,3.375000,41.906250,33.750000,1.968750,0.843750,0.000000,0.562500,1.125000,1.687500,0.000000,1.968750,0.562500,0.0
229,1707,Midfielder,A. Ochoa,Málaga,32,1024,0,12.0,5,0,18,4,3,3,3,65,401,312,48,17,2,16,0.0,0.000000,0.000000,0,0.000000,1.054688,0.439453,5.712891,35.244141,27.421875,4.218750,1.494141,0.175781,1.406250,1.582031,0.351562,0.263672,0.263672,0.263672,0.0
230,1708,Midfielder,A. Martín,Mirandés,36,1642,1,23.0,6,2,30,17,15,24,4,91,575,451,68,18,2,14,0.0,0.109622,0.054811,3,0.164434,1.260658,0.328867,4.987820,31.516443,24.719854,3.727162,0.986602,0.109622,0.767357,1.644336,0.931790,0.822168,1.315469,0.219245,0.0
231,1709,Midfielder,DFD. Fernández,CD Tenerife,15,316,0,6.0,1,1,8,0,1,4,3,27,76,55,3,4,0,2,0.0,0.284810,0.000000,1,0.284810,1.708861,0.284810,7.689873,21.645570,15.664557,0.854430,1.139241,0.000000,0.569620,2.278481,0.000000,0.284810,1.139241,0.854430,0.0

Removing NaN again and fixing decimal places

In [18]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,1478,Defender,J. Ángel,Sporting Gijón,38,1380,2,13.0,3,1,26,44,10,25,2,66,685,552,113,155,4,27,0.0,0.07,0.13,3,0.20,0.85,0.20,4.30,44.67,36.00,7.37,10.11,0.26,1.76,1.70,2.87,0.65,1.63,0.13,0.0
1,1479,Defender,J. Pulido,Huesca,37,3184,1,20.0,7,2,29,231,40,79,2,132,1579,1395,167,2,3,12,0.0,0.06,0.03,3,0.08,0.57,0.20,3.73,44.63,39.43,4.72,0.06,0.08,0.34,0.82,6.53,1.13,2.23,0.06,0.0
2,1480,Defender,M. Mateu,CD Tenerife,37,3218,5,24.0,7,2,36,83,23,12,5,91,1313,974,340,272,9,57,0.0,0.06,0.14,7,0.20,0.67,0.20,2.55,36.72,27.24,9.51,7.61,0.25,1.59,1.01,2.32,0.64,0.34,0.14,0.0
3,1481,Defender,N. Maraš,Mirandés,35,2026,1,11.0,2,0,30,124,17,66,1,108,982,828,120,2,2,9,0.0,0.00,0.04,1,0.04,0.49,0.09,4.80,43.62,36.78,5.33,0.09,0.09,0.40,1.33,5.51,0.76,2.93,0.04,0.0
4,1482,Defender,A. Arbilla,Eibar,30,2326,0,17.0,5,0,23,139,36,42,3,80,1703,1424,356,1,0,6,0.0,0.00,0.00,0,0.00,0.66,0.19,3.10,65.89,55.10,13.77,0.04,0.00,0.23,0.89,5.38,1.39,1.63,0.12,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,1705,Midfielder,A. Madariaga,Eibar,29,1405,0,28.0,12,3,25,20,17,26,4,86,609,486,33,14,2,13,0.0,0.19,0.00,3,0.19,1.79,0.77,5.51,39.01,31.13,2.11,0.90,0.13,0.83,1.60,1.28,1.09,1.67,0.26,0.0
228,1706,Midfielder,M. Cantero,Burgos Club de Fútbol,25,320,0,2.0,0,0,4,6,0,7,2,12,149,120,7,3,0,2,0.0,0.00,0.00,0,0.00,0.56,0.00,3.38,41.91,33.75,1.97,0.84,0.00,0.56,1.12,1.69,0.00,1.97,0.56,0.0
229,1707,Midfielder,A. Ochoa,Málaga,32,1024,0,12.0,5,0,18,4,3,3,3,65,401,312,48,17,2,16,0.0,0.00,0.00,0,0.00,1.05,0.44,5.71,35.24,27.42,4.22,1.49,0.18,1.41,1.58,0.35,0.26,0.26,0.26,0.0
230,1708,Midfielder,A. Martín,Mirandés,36,1642,1,23.0,6,2,30,17,15,24,4,91,575,451,68,18,2,14,0.0,0.11,0.05,3,0.16,1.26,0.33,4.99,31.52,24.72,3.73,0.99,0.11,0.77,1.64,0.93,0.82,1.32,0.22,0.0
231,1709,Midfielder,DFD. Fernández,CD Tenerife,15,316,0,6.0,1,1,8,0,1,4,3,27,76,55,3,4,0,2,0.0,0.28,0.00,1,0.28,1.71,0.28,7.69,21.65,15.66,0.85,1.14,0.00,0.57,2.28,0.00,0.28,1.14,0.85,0.0

Adding and moving "League" column

In [19]:
#label
leagueLabel = "LaLiga 2"

#adding label to df
finalData["League"] = leagueLabel

In [20]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,1478,Defender,LaLiga 2,J. Ángel,Sporting Gijón,38,1380,2,13.0,3,1,26,44,10,25,2,66,685,552,113,155,4,27,0.0,0.07,0.13,3,0.20,0.85,0.20,4.30,44.67,36.00,7.37,10.11,0.26,1.76,1.70,2.87,0.65,1.63,0.13,0.0
1,1479,Defender,LaLiga 2,J. Pulido,Huesca,37,3184,1,20.0,7,2,29,231,40,79,2,132,1579,1395,167,2,3,12,0.0,0.06,0.03,3,0.08,0.57,0.20,3.73,44.63,39.43,4.72,0.06,0.08,0.34,0.82,6.53,1.13,2.23,0.06,0.0
2,1480,Defender,LaLiga 2,M. Mateu,CD Tenerife,37,3218,5,24.0,7,2,36,83,23,12,5,91,1313,974,340,272,9,57,0.0,0.06,0.14,7,0.20,0.67,0.20,2.55,36.72,27.24,9.51,7.61,0.25,1.59,1.01,2.32,0.64,0.34,0.14,0.0
3,1481,Defender,LaLiga 2,N. Maraš,Mirandés,35,2026,1,11.0,2,0,30,124,17,66,1,108,982,828,120,2,2,9,0.0,0.00,0.04,1,0.04,0.49,0.09,4.80,43.62,36.78,5.33,0.09,0.09,0.40,1.33,5.51,0.76,2.93,0.04,0.0
4,1482,Defender,LaLiga 2,A. Arbilla,Eibar,30,2326,0,17.0,5,0,23,139,36,42,3,80,1703,1424,356,1,0,6,0.0,0.00,0.00,0,0.00,0.66,0.19,3.10,65.89,55.10,13.77,0.04,0.00,0.23,0.89,5.38,1.39,1.63,0.12,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,1705,Midfielder,LaLiga 2,A. Madariaga,Eibar,29,1405,0,28.0,12,3,25,20,17,26,4,86,609,486,33,14,2,13,0.0,0.19,0.00,3,0.19,1.79,0.77,5.51,39.01,31.13,2.11,0.90,0.13,0.83,1.60,1.28,1.09,1.67,0.26,0.0
228,1706,Midfielder,LaLiga 2,M. Cantero,Burgos Club de Fútbol,25,320,0,2.0,0,0,4,6,0,7,2,12,149,120,7,3,0,2,0.0,0.00,0.00,0,0.00,0.56,0.00,3.38,41.91,33.75,1.97,0.84,0.00,0.56,1.12,1.69,0.00,1.97,0.56,0.0
229,1707,Midfielder,LaLiga 2,A. Ochoa,Málaga,32,1024,0,12.0,5,0,18,4,3,3,3,65,401,312,48,17,2,16,0.0,0.00,0.00,0,0.00,1.05,0.44,5.71,35.24,27.42,4.22,1.49,0.18,1.41,1.58,0.35,0.26,0.26,0.26,0.0
230,1708,Midfielder,LaLiga 2,A. Martín,Mirandés,36,1642,1,23.0,6,2,30,17,15,24,4,91,575,451,68,18,2,14,0.0,0.11,0.05,3,0.16,1.26,0.33,4.99,31.52,24.72,3.73,0.99,0.11,0.77,1.64,0.93,0.82,1.32,0.22,0.0
231,1709,Midfielder,LaLiga 2,DFD. Fernández,CD Tenerife,15,316,0,6.0,1,1,8,0,1,4,3,27,76,55,3,4,0,2,0.0,0.28,0.00,1,0.28,1.71,0.28,7.69,21.65,15.66,0.85,1.14,0.00,0.57,2.28,0.00,0.28,1.14,0.85,0.0

In [21]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/LALIGA2complete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [22]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [23]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [24]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.00000,200.000000,200.00000,200.00000,200.000000,200.000000,200.000000,200.000000
mean,1593.720000,33.365000,1687.935000,1.190000,18.310000,5.985000,1.790000,27.745000,44.020000,14.880000,27.23000,4.560000,83.085000,676.395000,534.805000,107.160000,30.560000,2.010000,13.850000,5.390000,0.103400,0.066850,2.980000,0.169950,1.04540,0.338050,4.510800,34.943450,27.595700,5.193300,1.648850,0.10505,0.752850,1.51850,2.12335,0.753900,1.393800,0.270450,0.260000
std,69.929912,9.151531,970.287934,1.598963,19.097841,7.201673,2.578594,22.811219,49.327025,13.167479,27.95055,5.251121,56.972953,475.897321,400.777482,139.766799,44.485969,2.583267,14.073658,22.636252,0.154781,0.102205,3.542931,0.217975,0.90074,0.373145,1.983951,11.126833,10.736283,4.442703,1.972104,0.11974,0.585922,0.91913,1.78500,0.500942,1.087064,0.270518,0.856174
min,1478.000000,4.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,20.000000,13.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,11.700000,7.220000,0.280000,0.000000,0.00000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,1530.750000,29.000000,840.500000,0.000000,5.000000,1.000000,0.000000,12.000000,9.000000,4.000000,8.00000,1.000000,38.750000,300.250000,232.000000,24.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.40000,0.070000,3.495000,27.277500,19.232500,2.100000,0.150000,0.00000,0.287500,0.87000,0.74000,0.337500,0.627500,0.060000,0.000000
50%,1588.500000,36.500000,1614.500000,1.000000,12.000000,3.000000,1.000000,22.500000,26.500000,11.500000,18.00000,3.000000,74.000000,577.000000,443.500000,68.000000,10.000000,1.000000,9.000000,0.000000,0.045000,0.030000,2.000000,0.110000,0.70000,0.195000,4.575000,35.190000,27.510000,4.010000,0.785000,0.07000,0.690000,1.47000,1.48500,0.795000,1.210000,0.170000,0.000000
75%,1657.250000,40.000000,2400.000000,2.000000,25.250000,9.000000,2.000000,38.000000,63.000000,24.000000,37.00000,6.000000,114.500000,1018.750000,749.750000,124.500000,43.250000,3.000000,19.000000,0.000000,0.160000,0.110000,5.000000,0.252500,1.69000,0.507500,5.702500,42.387500,34.932500,6.772500,2.590000,0.17000,1.102500,2.10750,3.20000,1.107500,1.885000,0.430000,0.000000
max,1709.000000,45.000000,3978.000000,7.000000,103.000000,36.000000,13.000000,115.000000,270.000000,61.000000,176.00000,25.000000,242.000000,2580.000000,2220.000000,752.000000,272.000000,14.000000,76.000000,146.000000,1.100000,0.960000,17.000000,1.910000,5.28000,2.860000,10.120000,65.890000,59.470000,22.860000,10.110000,0.55000,2.900000,5.40000,7.84000,2.150000,6.060000,1.260000,4.000000

In [25]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/LALIGA2complete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [26]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [27]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.00000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000
mean,1596.000000,29.354430,1426.472574,1.004219,15.489451,5.063291,1.518987,23.468354,37.21097,12.582278,23.008439,3.848101,70.257384,571.388186,451.679325,90.573840,25.814346,1.696203,11.704641,4.552743,0.097679,0.056414,2.523207,0.153840,0.947004,0.300633,4.152743,30.785274,24.112743,4.662532,1.468354,0.088650,0.688650,1.401055,1.913966,0.739747,1.247342,0.228228,0.225865
std,68.560193,13.147183,1079.363790,1.530752,18.732192,6.954468,2.453953,23.198390,47.99565,13.224535,27.486976,5.099240,60.256349,500.834077,415.876212,134.040595,42.320700,2.482248,13.857221,20.877629,0.213381,0.096950,3.425430,0.258119,1.048206,0.393880,2.572591,14.915525,13.210931,4.697427,2.044623,0.116404,0.817576,1.098024,1.911688,0.954037,1.195012,0.267178,0.796294
min,1478.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1537.000000,19.000000,514.000000,0.000000,2.000000,0.000000,0.000000,4.000000,5.00000,1.000000,3.000000,0.000000,17.000000,149.000000,119.000000,13.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.220000,0.000000,3.040000,21.810000,14.970000,1.300000,0.000000,0.000000,0.090000,0.720000,0.470000,0.140000,0.300000,0.000000,0.000000
50%,1596.000000,35.000000,1331.000000,0.000000,9.000000,2.000000,0.000000,18.000000,18.00000,8.000000,14.000000,2.000000,61.000000,457.000000,352.000000,49.000000,5.000000,1.000000,7.000000,0.000000,0.000000,0.000000,1.000000,0.080000,0.600000,0.160000,4.370000,32.800000,24.720000,3.640000,0.530000,0.040000,0.550000,1.330000,1.180000,0.670000,1.030000,0.130000,0.000000
75%,1655.000000,39.000000,2326.000000,1.000000,21.000000,7.000000,2.000000,36.000000,52.00000,21.000000,32.000000,5.000000,109.000000,908.000000,677.000000,113.000000,36.000000,2.000000,17.000000,0.000000,0.130000,0.090000,4.000000,0.220000,1.530000,0.460000,5.620000,40.650000,33.750000,6.440000,2.470000,0.140000,1.040000,2.010000,2.900000,1.060000,1.790000,0.370000,0.000000
max,1714.000000,45.000000,3978.000000,7.000000,103.000000,36.000000,13.000000,115.000000,270.00000,61.000000,176.000000,25.000000,242.000000,2580.000000,2220.000000,752.000000,272.000000,14.000000,76.000000,146.000000,2.470000,0.960000,17.000000,2.470000,7.400000,2.860000,15.000000,65.890000,59.470000,27.460000,12.860000,0.550000,9.000000,6.000000,9.000000,11.250000,7.500000,1.260000,4.000000

In [28]:
#We can see that the 25% cutoff is 514
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 514].index)

In [29]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000
mean,1587.819209,34.265537,1864.661017,1.316384,20.135593,6.576271,1.960452,30.700565,49.316384,16.638418,30.502825,5.016949,92.163842,749.056497,592.497175,118.282486,33.836158,2.237288,15.333333,5.745763,0.098870,0.065650,3.276836,0.164237,1.046497,0.336045,4.659209,35.489944,28.136271,5.069153,1.675932,0.112203,0.777458,1.549379,2.274294,0.803616,1.507627,0.268136,0.177345
std,70.538038,8.172334,888.150465,1.651932,19.456061,7.388266,2.667910,22.549835,50.047380,12.985319,28.082898,5.396205,54.119410,457.390706,389.793187,144.706244,46.220092,2.654364,14.267201,23.991660,0.125765,0.080169,3.634928,0.163383,0.832896,0.329566,1.811871,11.083386,10.646135,4.127994,2.002103,0.118462,0.582776,0.843878,1.820859,0.491932,1.086234,0.258247,0.698408
min,1478.000000,12.000000,519.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,81.000000,50.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.700000,7.220000,0.280000,0.000000,0.000000,0.000000,0.000000,0.180000,0.000000,0.000000,0.000000,0.000000
25%,1525.000000,30.000000,1121.000000,0.000000,7.000000,2.000000,0.000000,14.000000,13.000000,6.000000,12.000000,1.000000,48.000000,401.000000,297.000000,30.000000,3.000000,0.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.030000,0.430000,0.080000,3.690000,27.880000,19.850000,2.200000,0.160000,0.000000,0.320000,0.950000,0.850000,0.380000,0.710000,0.080000,0.000000
50%,1578.000000,37.000000,1773.000000,1.000000,14.000000,4.000000,1.000000,25.000000,33.000000,14.000000,20.000000,3.000000,87.000000,656.000000,517.000000,83.000000,14.000000,1.000000,11.000000,0.000000,0.060000,0.040000,2.000000,0.120000,0.730000,0.200000,4.610000,35.720000,28.060000,4.210000,0.780000,0.080000,0.720000,1.500000,1.720000,0.830000,1.290000,0.170000,0.000000
75%,1655.000000,40.000000,2500.000000,2.000000,29.000000,9.000000,3.000000,41.000000,68.000000,26.000000,40.000000,6.000000,122.000000,1080.000000,828.000000,136.000000,50.000000,3.000000,21.000000,0.000000,0.150000,0.110000,5.000000,0.260000,1.690000,0.500000,5.710000,43.620000,36.510000,6.600000,2.590000,0.170000,1.120000,2.080000,3.390000,1.140000,2.030000,0.410000,0.000000
max,1708.000000,45.000000,3978.000000,7.000000,103.000000,36.000000,13.000000,115.000000,270.000000,61.000000,176.000000,25.000000,242.000000,2580.000000,2220.000000,752.000000,272.000000,14.000000,76.000000,146.000000,0.600000,0.380000,17.000000,0.720000,3.660000,1.250000,10.120000,65.890000,55.100000,22.860000,10.110000,0.550000,2.900000,4.130000,7.840000,2.150000,6.060000,1.260000,3.560000

In [30]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/LALIGA2complete25.csv")