Please remember that the only differences in this file are stated within "dataCleaningMAIN.ipynb", just to save time reading over the same lines of code and analysis.

Comments inbetween code will be kept to a minimum (unless needed), as all justification of the work process is within "dataCleaningMAIN.ipynb".

# 1.1 Data Exploration

In [1]:
#importing basics
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from functools import reduce

In [2]:
#initiating every dataframe at once
pd.set_option('display.max_columns', None)

#DEFENDER
dfDatt = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBdefenderATTACKING.csv")
dfDdft = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBdefenderDEFAULT.csv")
dfDdef = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBdefenderDEFENDING.csv")
dfDpas = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBdefenderPASSING.csv")

#FORWARD
dfFatt = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBforwardATTACKING.csv")
dfFdft = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBforwardDEFAULT.csv")
dfFdef = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBforwardDEFENDING.csv")
dfFpas = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBforwardPASSING.csv")

#GOALKEEPER
dfGatt = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBgoalkeeperATTACKING.csv")
dfGdft = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBgoalkeeperDEFAULT.csv")
dfGdef = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBgoalkeeperDEFENDING.csv")
dfGgoa = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBgoalkeeperGOALKEEPING.csv") 
dfGpas = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBgoalkeeperPASSING.csv")

#MIDFIELDER
dfMatt = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBmidfielderATTACKING.csv")
dfMdft = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBmidfielderDEFAULT.csv")
dfMdef = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBmidfielderDEFENDING.csv")
dfMpas = pd.read_csv("data/finalSCRAPEDdata/serieb/SEBmidfielderPASSING.csv")

In [3]:
#arrays for renaming
attackingColumns = ["Name", "Team", "Assists", "bigChancesCreated", "Shots", "shotsOnTarget", "Goals", "Mins", "xG", "npxG", "xA", "unnamed"]
defaultColumns = ["Name", "Team", "App", "Goals", "Mins", "xG", "xA", "unnamed"]
defendingColumns = ["Name", "Team", "Tackles", "Clearances", "Interceptions", "aerialsWon", "Blocks", "Mins", "duelsWon", "unnamed"]
passingColumns = ["Name", "Team", "Passes", "accuratePasses", "longBalls", "Assists", "Crosses", "bigChancesCreated", "Mins", "keyPasses", "unnamed"]
goalkeepingColumns = ["Name", "Team", "Mins", "Saves", "unnamed"]

#attacking
for df in [dfFatt, dfGatt, dfMatt, dfDatt]:
    df.columns = attackingColumns

#default
for df in [dfFdft, dfGdft, dfMdft, dfDdft]:
    df.columns = defaultColumns

#defending
for df in [dfFdef, dfGdef, dfMdef, dfDdef]:
    df.columns = defendingColumns

#passing
for df in [dfFpas, dfGpas, dfMpas, dfDpas]:
    df.columns = passingColumns

#goalkeeping
for df in [dfGgoa]:
    df.columns = goalkeepingColumns

In [4]:
#only unnamed is expected here
dfDdef.isnull().sum()

Name              0
Team              0
Tackles           0
Clearances        0
Interceptions     0
aerialsWon        0
Blocks            0
Mins              0
duelsWon          0
unnamed          40
dtype: int64

In [5]:
dfDdef.describe()

,Tackles,Clearances,Interceptions,aerialsWon,Blocks,Mins,duelsWon,unnamed
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,0.0
mean,25.025000,78.250000,16.475000,43.350000,2.050000,1498.100000,88.300000,NaN
std,18.713066,57.707374,13.177268,36.827073,2.620922,965.395091,61.942157,NaN
min,0.000000,0.000000,0.000000,1.000000,0.000000,35.000000,1.000000,NaN
25%,9.000000,25.000000,5.000000,12.500000,0.000000,597.000000,25.250000,NaN
50%,24.500000,68.000000,14.500000,32.000000,1.000000,1475.500000,77.500000,NaN
75%,37.250000,118.750000,24.000000,64.250000,3.000000,2284.000000,134.500000,NaN
max,71.000000,210.000000,49.000000,121.000000,14.000000,3112.000000,203.000000,NaN

# 1.2 Data Pre-processing

### 1.2.1 Data Erasure

In [6]:
#arrays for dropping columns
defaultDropColumns = ["Goals", "xG", "xA", "unnamed"]
defendingDropColumns = ["Mins", "unnamed"]
attackingDropColumns = ["bigChancesCreated", "Mins", "unnamed"]
passingDropColumns = ["Assists", "Mins", "unnamed"]

#Every default filter dataframe
for df in [dfDdft, dfFdft, dfGdft, dfMdft]:
    df.drop(columns=defaultDropColumns, inplace=True)

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=defendingDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=attackingDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=passingDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Mins", "unnamed"])

To add the unique identifier first we need to go back to the previous leagues master database to find the final id, in this case located within BULIcomplete.csv we can see the final id is 465.

In [7]:
#starting with defenders
dfDdft["ID"] = (dfDdft.index + 3339)
dfDdef["ID"] = (dfDdef.index + 3339)
dfDatt["ID"] = (dfDatt.index + 3339)
dfDpas["ID"] = (dfDpas.index + 3339) #should end at id no 3378
#dfDdft.head(300) - to check final id number

#next position alphabetically is forwards, so we find the max value for the defenders id
defFinalID = dfDdft["ID"].max()

#forwards id
dfFdft["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdft))
dfFdef["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFdef))
dfFatt["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFatt))
dfFpas["ID"] = range(defFinalID + 1, defFinalID + 1 + len(dfFpas)) #should end at id no. 3407
#dfFdft.head(300) - to check final id number

#repeat of finding the forwards id this time
forFinalID = dfFdft["ID"].max()

#goalkeepers id
dfGdft["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdft))
dfGdef["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGdef))
dfGatt["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGatt))
dfGpas["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGpas))
dfGgoa["ID"] = range(forFinalID +1, forFinalID +1 +len(dfGgoa)) #should end at id no. 3425
#dfGdft.head(300) - to check final id number

#repeat of finding the goalkeepers id this time
goaFinalId = dfGdft["ID"].max()

#midfielders id
dfMdft["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdft))
dfMdef["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMdef))
dfMatt["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMatt))
dfMpas["ID"] = range(goaFinalId + 1, goaFinalId + 1 +len(dfMpas)) #should end at id no. 3473
dfMdft.head(300) #to check final id number

                     Name            Team  App  Mins    ID
0             L. Cigarini        Reggiana   26   126  3426
1               P. Obiang           Monza   37  1492  3427
2                M. Maita       Benevento   36  2702  3428
3               S. Branca      Cittadella   22  1486  3429
4                 A. Vita      Cittadella   33  2591  3430
5            L. Garritano         Cosenza   26   759  3431
6                J. Mauri         Cosenza   18   306  3432
7                 P. Azzi           Monza   20  1533  3433
8                F. Gelli       Frosinone   33  1719  3434
9                M. Marin            Pisa   34  2646  3435
10         E. Masciangelo       Frosinone   36  2671  3436
11               I. Touré            Pisa   36  2435  3437
12            F. Caligara         Pescara   27   541  3438
13                G. Calò       Frosinone   35  2622  3439
14           M. Collocolo       Cremonese   35  2644  3440
15               M. Léris            Pisa    4   169  3441
16         A. Rizzo Pinna          Ascoli   37  1435  3442
17                M. Meli         Crotone   40   541  3443
18           L. Benedetti  Virtus Entella   30  1142  3444
19               M. Rover        Reggiana   36  1408  3445
20          M. Bertagnoli        Reggiana   34  1492  3446
21             N. Corrado       Frosinone   38  1979  3447
22        L. Belardinelli        Reggiana   15   483  3448
23            T. Reinhart        Reggiana   36  2233  3449
24               R. Celia       Benevento   38  1531  3450
25             N. Galazzi           Monza   24  1469  3451
26           G. Piccinini            Pisa   38  2341  3452
27            K. Bozhanaj        Reggiana   35   914  3453
28            F. Amatucci      Cittadella   37  2812  3454
29            T. Barbieri       Cremonese   39  2109  3455
30         GCG. Corradini          Ascoli    1     0  3456
31            T. Milanese       Cremonese   37   436  3457
32             M. Højholt            Pisa   38  1269  3458
33                 Y. Paz        Reggiana   34   440  3459
34               R. Kouda           Parma   27   838  3460
35            F. Casolari      Cittadella   29  1260  3461
36         C. Kourfalidis         Cosenza   35  1093  3462
37               G. Olzer         Pescara   32  1205  3463
38             A. Oliveri         Pescara   31  1754  3464
39               A. Fiori       Frosinone   36  1831  3465
40            A. Florenzi         Cosenza   30  2182  3466
41  R. Floriani Mussolini       Cremonese   37  2890  3467
42               J. Oyono       Frosinone   38  1585  3468
43              S. Angori            Pisa   38  2354  3469
44               I. Vural            Pisa   36  1196  3470
45           L. Mendicino        Reggiana   36   521  3471
46            M. Cichella       Frosinone   34  1021  3472
47          ECE. Contiero         Cosenza    4     8  3473

#### Further Data Erasure

In [8]:
#array for dropping name and team
nameAndTeamDropColumns = ["Name", "Team"]

#Every defending filter dataframe
for df in [dfDdef, dfFdef, dfGdef, dfMdef]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every attacking filter dataframe
for df in [dfDatt, dfFatt, dfGatt, dfMatt]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every passing filter dataframe
for df in [dfDpas, dfFpas, dfGpas, dfMpas]:
    df.drop(columns=nameAndTeamDropColumns, inplace=True)

#Every goalkeeping dataframe
dfGgoa =  dfGgoa.drop(columns=["Name", "Team"])

#### Dataframe Merging

In [9]:
#merging defenders
defenderDFs = [dfDdft, dfDatt, dfDdef, dfDpas]

defendersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), defenderDFs)

#merging forwards
forwardDFs = [dfFdft, dfFatt, dfFdef, dfFpas]

forwardsMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), forwardDFs)

#merging goalkeepers
goalkeeperDFs = [dfGdft, dfGatt, dfGdef, dfGpas, dfGgoa]

goalkeepersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), goalkeeperDFs)

#merging midfielders
midfielderDFs = [dfMdft, dfMatt, dfMdef, dfMpas]

midfieldersMerged = reduce(lambda left,right: pd.merge(left,right, on="ID", how="outer"), midfielderDFs)

Adding positon labels

In [10]:
#adding defender column
#creating label
defenderPosition = "Defender"
#adding label to df
defendersMerged["Position"] = defenderPosition

#adding forward column
#creating label
forwardPosition = "Forward"
#adding label to df
forwardsMerged["Position"] = forwardPosition

#adding goalkeeper column
#creating label
goalkeeperPosition = "Goalkeeper"
#adding label to df
goalkeepersMerged["Position"] = goalkeeperPosition

#adding midfielder column
#creating label
midfielderPosition = "Midfielder"
#adding label to df
midfieldersMerged["Position"] = midfielderPosition

Positional mergers

In [11]:
#Just as a precaution, we can save the merged datasets under separate csvs if needed for some reason

defendersMerged.to_csv("data/finalSCRAPEDdata/serieb/SEBdefender.csv", index=None)
forwardsMerged.to_csv("data/finalSCRAPEDdata/serieb/SEBforward.csv", index=None)
goalkeepersMerged.to_csv("data/finalSCRAPEDdata/serieb/SEBgoalkeeper.csv", index=None)
midfieldersMerged.to_csv("data/finalSCRAPEDdata/serieb/SEBmidfielder.csv", index=None)

Master merge

In [12]:
#merging everything
positionDFs = [defendersMerged, forwardsMerged, goalkeepersMerged, midfieldersMerged]

finalData = pd.concat(positionDFs, ignore_index=True)

finalData.head(300)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,A. Caracciolo,Pisa,36,3032,3339,0,25.0,4,2,0.0,NaN,0.0,71,210,49,91,5,173,1356,1162,166,3,2,6,Defender,NaN
1,A. Salvi,Cittadella,36,2359,3340,2,20.0,6,0,0.0,NaN,0.0,33,132,34,63,3,130,1017,745,247,47,3,11,Defender,NaN
2,P. Rozzio,Reggiana,19,1217,3341,0,7.0,3,0,0.0,NaN,0.0,11,106,16,53,3,78,617,557,66,0,0,4,Defender,NaN
3,F. Lucioni,Frosinone,13,388,3342,1,5.0,2,0,0.0,NaN,0.0,4,40,0,9,0,14,151,125,37,0,1,3,Defender,NaN
4,F. Ceccherini,Cremonese,30,1548,3343,1,10.0,4,1,0.0,NaN,0.0,22,83,24,60,1,113,1001,905,84,5,2,4,Defender,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,S. Angori,Pisa,38,2354,3469,3,28.0,5,2,0.0,NaN,0.0,27,72,9,40,11,133,759,580,107,192,9,55,Midfielder,NaN
131,I. Vural,Pisa,36,1196,3470,1,14.0,2,0,0.0,NaN,0.0,25,20,8,15,2,91,414,361,25,2,2,10,Midfielder,NaN
132,L. Mendicino,Reggiana,36,521,3471,0,1.0,0,0,0.0,NaN,0.0,28,10,4,4,1,39,264,231,25,1,0,2,Midfielder,NaN
133,M. Cichella,Frosinone,34,1021,3472,0,7.0,1,1,0.0,NaN,0.0,24,7,8,2,2,38,478,429,40,3,0,5,Midfielder,NaN
134,ECE. Contiero,Cosenza,4,8,3473,0,NaN,0,0,0.0,NaN,0.0,0,0,0,0,0,0,8,7,0,0,0,0,Midfielder,NaN

### 1.2.2 Further Data Cleaning

Removing NaN

In [13]:
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns

finalData[numberColumns] = finalData[numberColumns].fillna(0)

finalData.head(-5)

,Name,Team,App,Mins,ID,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Position,Saves
0,A. Caracciolo,Pisa,36,3032,3339,0,25.0,4,2,0.0,0.0,0.0,71,210,49,91,5,173,1356,1162,166,3,2,6,Defender,0.0
1,A. Salvi,Cittadella,36,2359,3340,2,20.0,6,0,0.0,0.0,0.0,33,132,34,63,3,130,1017,745,247,47,3,11,Defender,0.0
2,P. Rozzio,Reggiana,19,1217,3341,0,7.0,3,0,0.0,0.0,0.0,11,106,16,53,3,78,617,557,66,0,0,4,Defender,0.0
3,F. Lucioni,Frosinone,13,388,3342,1,5.0,2,0,0.0,0.0,0.0,4,40,0,9,0,14,151,125,37,0,1,3,Defender,0.0
4,F. Ceccherini,Cremonese,30,1548,3343,1,10.0,4,1,0.0,0.0,0.0,22,83,24,60,1,113,1001,905,84,5,2,4,Defender,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,A. Oliveri,Pescara,31,1754,3464,2,25.0,3,0,0.0,0.0,0.0,38,34,15,28,9,127,594,491,34,87,3,23,Midfielder,0.0
126,A. Fiori,Frosinone,36,1831,3465,5,58.0,19,2,0.0,0.0,0.0,17,10,6,8,21,110,578,488,22,46,5,30,Midfielder,0.0
127,A. Florenzi,Cosenza,30,2182,3466,2,41.0,10,2,0.0,0.0,0.0,37,39,23,19,11,142,965,768,56,58,4,34,Midfielder,0.0
128,R. Floriani Mussolini,Cremonese,37,2890,3467,2,16.0,8,1,0.0,0.0,0.0,44,92,21,43,1,119,529,351,68,92,5,18,Midfielder,0.0
129,J. Oyono,Frosinone,38,1585,3468,0,6.0,3,1,0.0,0.0,0.0,36,49,6,21,0,105,596,484,54,43,1,18,Midfielder,0.0

Moving "ID" and "Position" rows

In [14]:
#id
finalData.insert(0, "ID", finalData.pop("ID"))
#position
finalData.insert(1, "Position", finalData.pop("Position"))

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
0,3339,Defender,A. Caracciolo,Pisa,36,3032,0,25.0,4,2,0.0,0.0,0.0,71,210,49,91,5,173,1356,1162,166,3,2,6,0.0
1,3340,Defender,A. Salvi,Cittadella,36,2359,2,20.0,6,0,0.0,0.0,0.0,33,132,34,63,3,130,1017,745,247,47,3,11,0.0
2,3341,Defender,P. Rozzio,Reggiana,19,1217,0,7.0,3,0,0.0,0.0,0.0,11,106,16,53,3,78,617,557,66,0,0,4,0.0
3,3342,Defender,F. Lucioni,Frosinone,13,388,1,5.0,2,0,0.0,0.0,0.0,4,40,0,9,0,14,151,125,37,0,1,3,0.0
4,3343,Defender,F. Ceccherini,Cremonese,30,1548,1,10.0,4,1,0.0,0.0,0.0,22,83,24,60,1,113,1001,905,84,5,2,4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,3464,Midfielder,A. Oliveri,Pescara,31,1754,2,25.0,3,0,0.0,0.0,0.0,38,34,15,28,9,127,594,491,34,87,3,23,0.0
126,3465,Midfielder,A. Fiori,Frosinone,36,1831,5,58.0,19,2,0.0,0.0,0.0,17,10,6,8,21,110,578,488,22,46,5,30,0.0
127,3466,Midfielder,A. Florenzi,Cosenza,30,2182,2,41.0,10,2,0.0,0.0,0.0,37,39,23,19,11,142,965,768,56,58,4,34,0.0
128,3467,Midfielder,R. Floriani Mussolini,Cremonese,37,2890,2,16.0,8,1,0.0,0.0,0.0,44,92,21,43,1,119,529,351,68,92,5,18,0.0
129,3468,Midfielder,J. Oyono,Frosinone,38,1585,0,6.0,3,1,0.0,0.0,0.0,36,49,6,21,0,105,596,484,54,43,1,18,0.0

Checking if expected stats exist

In [15]:
finalData.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,xG,npxG,xA,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves
count,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.0,135.0,135.0,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000
mean,3406.000000,28.422222,1297.340741,0.992593,15.866667,4.562963,1.200000,0.0,0.0,0.0,20.066667,36.777778,9.955556,25.814815,4.518519,71.007407,513.570370,408.066667,76.614815,26.192593,1.570370,11.696296,3.925926
std,39.115214,10.582629,948.600494,1.363141,16.536166,5.469873,1.946294,0.0,0.0,0.0,19.126523,44.649492,11.050675,31.203039,5.404326,58.688718,457.406699,382.077788,124.889861,38.989378,2.114417,12.472821,17.016949
min,3339.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3372.500000,21.000000,478.000000,0.000000,2.000000,0.000000,0.000000,0.0,0.0,0.0,3.000000,5.000000,0.500000,4.000000,0.000000,17.000000,143.000000,107.500000,9.500000,1.000000,0.000000,2.000000,0.000000
50%,3406.000000,33.000000,1217.000000,0.000000,10.000000,2.000000,0.000000,0.0,0.0,0.0,16.000000,21.000000,6.000000,15.000000,3.000000,62.000000,432.000000,319.000000,36.000000,12.000000,1.000000,7.000000,0.000000
75%,3439.500000,37.000000,2026.000000,2.000000,25.000000,8.000000,2.000000,0.0,0.0,0.0,33.500000,53.000000,16.000000,35.500000,7.000000,112.000000,780.500000,587.500000,95.500000,35.000000,2.000000,18.000000,0.000000
max,3473.000000,40.000000,3598.000000,6.000000,67.000000,23.000000,13.000000,0.0,0.0,0.0,84.000000,210.000000,49.000000,169.000000,25.000000,275.000000,1888.000000,1698.000000,839.000000,226.000000,10.000000,55.000000,111.000000

There are no expected stats captured within this dataset, so we remove them

In [16]:
finalData = finalData.drop(columns=["xG", "npxG", "xA"])

Adding additional data fields

In [17]:
#Adding per90 stats - grouped for visual reason
#attacking orientated stats
#goals per90
finalData["goalsPer90"] = finalData["Goals"] / finalData["Mins"] * 90
#assists per90
finalData["assistsPer90"] = finalData["Assists"] / finalData["Mins"] * 90
#goals+assists (to make per90)
finalData["g+a"] = finalData["Assists"] + finalData["Goals"]
#goals+assists per 90
finalData["g+aPer90"] = finalData["g+a"] / finalData["Mins"] * 90
#shots per 90
finalData["shotsPer90"] = finalData["Shots"] / finalData["Mins"] * 90
#shotsOnTarget per 90
finalData["shotsOnTargetPer90"] = finalData["shotsOnTarget"] / finalData["Mins"] * 90
#duelsWon per 90
finalData["duelsWonPer90"] = finalData["duelsWon"] / finalData["Mins"] * 90

#passing orientated stats
#passes per 90
finalData["passesPer90"] = finalData["Passes"] / finalData["Mins"] * 90
#accuratePasses per 90
finalData["accuratePassesPer90"] = finalData["accuratePasses"] / finalData["Mins"] * 90
#longBalls per 90
finalData["longBallsPer90"] = finalData["longBalls"] / finalData["Mins"] * 90
#crosses per 90
finalData["crossesPer90"] = finalData["Crosses"] / finalData["Mins"] * 90
#bigChancesCreated per 90
finalData["bigChancesCreatedPer90"] = finalData["bigChancesCreated"] / finalData["Mins"] * 90
#keyPasses per 90
finalData["keyPassesPer90"] = finalData["keyPasses"] / finalData["Mins"] * 90
 
#defending orientated stats
#tackles per 90
finalData["tacklesPer90"] = finalData["Tackles"] / finalData["Mins"] * 90
#clearances per 90
finalData["clearancesPer90"] = finalData["Clearances"] / finalData["Mins"] * 90
#interceptions per 90
finalData["interceptionsPer90"] = finalData["Interceptions"] / finalData["Mins"] * 90
#aerialsWon per 90
finalData["aerialsWonPer90"] = finalData["aerialsWon"] / finalData["Mins"] * 90
#blocks per 90
finalData["blocksPer90"] = finalData["Blocks"] / finalData["Mins"] * 90
#savse per 90 - only goalkeeping stat available to us
finalData["savesPer90"] = finalData["Saves"] / finalData["Mins"] * 90


finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,3339,Defender,A. Caracciolo,Pisa,36,3032,0,25.0,4,2,71,210,49,91,5,173,1356,1162,166,3,2,6,0.0,0.059367,0.000000,2,0.059367,0.742084,0.118734,5.135224,40.250660,34.492084,4.927441,0.089050,0.059367,0.178100,2.107520,6.233509,1.454485,2.701187,0.148417,0.0
1,3340,Defender,A. Salvi,Cittadella,36,2359,2,20.0,6,0,33,132,34,63,3,130,1017,745,247,47,3,11,0.0,0.000000,0.076304,2,0.076304,0.763035,0.228911,4.959729,38.800339,28.423061,9.423485,1.793133,0.114455,0.419669,1.259008,5.036032,1.297160,2.403561,0.114455,0.0
2,3341,Defender,P. Rozzio,Reggiana,19,1217,0,7.0,3,0,11,106,16,53,3,78,617,557,66,0,0,4,0.0,0.000000,0.000000,0,0.000000,0.517666,0.221857,5.768283,45.628595,41.191454,4.880855,0.000000,0.000000,0.295809,0.813476,7.838948,1.183237,3.919474,0.221857,0.0
3,3342,Defender,F. Lucioni,Frosinone,13,388,1,5.0,2,0,4,40,0,9,0,14,151,125,37,0,1,3,0.0,0.000000,0.231959,1,0.231959,1.159794,0.463918,3.247423,35.025773,28.994845,8.582474,0.000000,0.231959,0.695876,0.927835,9.278351,0.000000,2.087629,0.000000,0.0
4,3343,Defender,F. Ceccherini,Cremonese,30,1548,1,10.0,4,1,22,83,24,60,1,113,1001,905,84,5,2,4,0.0,0.058140,0.058140,2,0.116279,0.581395,0.232558,6.569767,58.197674,52.616279,4.883721,0.290698,0.116279,0.232558,1.279070,4.825581,1.395349,3.488372,0.058140,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,3464,Midfielder,A. Oliveri,Pescara,31,1754,2,25.0,3,0,38,34,15,28,9,127,594,491,34,87,3,23,0.0,0.000000,0.102623,2,0.102623,1.282782,0.153934,6.516534,30.478905,25.193843,1.744584,4.464082,0.153934,1.180160,1.949829,1.744584,0.769669,1.436716,0.461802,0.0
126,3465,Midfielder,A. Fiori,Frosinone,36,1831,5,58.0,19,2,17,10,6,8,21,110,578,488,22,46,5,30,0.0,0.098307,0.245767,7,0.344074,2.850901,0.933916,5.406881,28.410705,23.986892,1.081376,2.261060,0.245767,1.474604,0.835609,0.491535,0.294921,0.393228,1.032223,0.0
127,3466,Midfielder,A. Florenzi,Cosenza,30,2182,2,41.0,10,2,37,39,23,19,11,142,965,768,56,58,4,34,0.0,0.082493,0.082493,4,0.164986,1.691109,0.412466,5.857012,39.802933,31.677360,2.309808,2.392301,0.164986,1.402383,1.526123,1.608616,0.948671,0.783685,0.453712,0.0
128,3467,Midfielder,R. Floriani Mussolini,Cremonese,37,2890,2,16.0,8,1,44,92,21,43,1,119,529,351,68,92,5,18,0.0,0.031142,0.062284,3,0.093426,0.498270,0.249135,3.705882,16.474048,10.930796,2.117647,2.865052,0.155709,0.560554,1.370242,2.865052,0.653979,1.339100,0.031142,0.0
129,3468,Midfielder,J. Oyono,Frosinone,38,1585,0,6.0,3,1,36,49,6,21,0,105,596,484,54,43,1,18,0.0,0.056782,0.000000,1,0.056782,0.340694,0.170347,5.962145,33.842271,27.482650,3.066246,2.441640,0.056782,1.022082,2.044164,2.782334,0.340694,1.192429,0.000000,0.0

Removing NaN again and fixing decimal places

In [18]:
#fill NaN rows with 0 (reused code)
numberColumns = finalData.select_dtypes(include=["float64", "int64"]).columns
finalData[numberColumns] = finalData[numberColumns].fillna(0)

#round decimals to 2
finalData = finalData.round(decimals=2)

finalData.head(-5)

,ID,Position,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,3339,Defender,A. Caracciolo,Pisa,36,3032,0,25.0,4,2,71,210,49,91,5,173,1356,1162,166,3,2,6,0.0,0.06,0.00,2,0.06,0.74,0.12,5.14,40.25,34.49,4.93,0.09,0.06,0.18,2.11,6.23,1.45,2.70,0.15,0.0
1,3340,Defender,A. Salvi,Cittadella,36,2359,2,20.0,6,0,33,132,34,63,3,130,1017,745,247,47,3,11,0.0,0.00,0.08,2,0.08,0.76,0.23,4.96,38.80,28.42,9.42,1.79,0.11,0.42,1.26,5.04,1.30,2.40,0.11,0.0
2,3341,Defender,P. Rozzio,Reggiana,19,1217,0,7.0,3,0,11,106,16,53,3,78,617,557,66,0,0,4,0.0,0.00,0.00,0,0.00,0.52,0.22,5.77,45.63,41.19,4.88,0.00,0.00,0.30,0.81,7.84,1.18,3.92,0.22,0.0
3,3342,Defender,F. Lucioni,Frosinone,13,388,1,5.0,2,0,4,40,0,9,0,14,151,125,37,0,1,3,0.0,0.00,0.23,1,0.23,1.16,0.46,3.25,35.03,28.99,8.58,0.00,0.23,0.70,0.93,9.28,0.00,2.09,0.00,0.0
4,3343,Defender,F. Ceccherini,Cremonese,30,1548,1,10.0,4,1,22,83,24,60,1,113,1001,905,84,5,2,4,0.0,0.06,0.06,2,0.12,0.58,0.23,6.57,58.20,52.62,4.88,0.29,0.12,0.23,1.28,4.83,1.40,3.49,0.06,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,3464,Midfielder,A. Oliveri,Pescara,31,1754,2,25.0,3,0,38,34,15,28,9,127,594,491,34,87,3,23,0.0,0.00,0.10,2,0.10,1.28,0.15,6.52,30.48,25.19,1.74,4.46,0.15,1.18,1.95,1.74,0.77,1.44,0.46,0.0
126,3465,Midfielder,A. Fiori,Frosinone,36,1831,5,58.0,19,2,17,10,6,8,21,110,578,488,22,46,5,30,0.0,0.10,0.25,7,0.34,2.85,0.93,5.41,28.41,23.99,1.08,2.26,0.25,1.47,0.84,0.49,0.29,0.39,1.03,0.0
127,3466,Midfielder,A. Florenzi,Cosenza,30,2182,2,41.0,10,2,37,39,23,19,11,142,965,768,56,58,4,34,0.0,0.08,0.08,4,0.16,1.69,0.41,5.86,39.80,31.68,2.31,2.39,0.16,1.40,1.53,1.61,0.95,0.78,0.45,0.0
128,3467,Midfielder,R. Floriani Mussolini,Cremonese,37,2890,2,16.0,8,1,44,92,21,43,1,119,529,351,68,92,5,18,0.0,0.03,0.06,3,0.09,0.50,0.25,3.71,16.47,10.93,2.12,2.87,0.16,0.56,1.37,2.87,0.65,1.34,0.03,0.0
129,3468,Midfielder,J. Oyono,Frosinone,38,1585,0,6.0,3,1,36,49,6,21,0,105,596,484,54,43,1,18,0.0,0.06,0.00,1,0.06,0.34,0.17,5.96,33.84,27.48,3.07,2.44,0.06,1.02,2.04,2.78,0.34,1.19,0.00,0.0

Adding and moving "League" column

In [19]:
#label
leagueLabel = "Serie B"

#adding label to df
finalData["League"] = leagueLabel

In [20]:
#moving league
finalData.insert(2, "League", finalData.pop("League"))

finalData.head(-5)

,ID,Position,League,Name,Team,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
0,3339,Defender,Serie B,A. Caracciolo,Pisa,36,3032,0,25.0,4,2,71,210,49,91,5,173,1356,1162,166,3,2,6,0.0,0.06,0.00,2,0.06,0.74,0.12,5.14,40.25,34.49,4.93,0.09,0.06,0.18,2.11,6.23,1.45,2.70,0.15,0.0
1,3340,Defender,Serie B,A. Salvi,Cittadella,36,2359,2,20.0,6,0,33,132,34,63,3,130,1017,745,247,47,3,11,0.0,0.00,0.08,2,0.08,0.76,0.23,4.96,38.80,28.42,9.42,1.79,0.11,0.42,1.26,5.04,1.30,2.40,0.11,0.0
2,3341,Defender,Serie B,P. Rozzio,Reggiana,19,1217,0,7.0,3,0,11,106,16,53,3,78,617,557,66,0,0,4,0.0,0.00,0.00,0,0.00,0.52,0.22,5.77,45.63,41.19,4.88,0.00,0.00,0.30,0.81,7.84,1.18,3.92,0.22,0.0
3,3342,Defender,Serie B,F. Lucioni,Frosinone,13,388,1,5.0,2,0,4,40,0,9,0,14,151,125,37,0,1,3,0.0,0.00,0.23,1,0.23,1.16,0.46,3.25,35.03,28.99,8.58,0.00,0.23,0.70,0.93,9.28,0.00,2.09,0.00,0.0
4,3343,Defender,Serie B,F. Ceccherini,Cremonese,30,1548,1,10.0,4,1,22,83,24,60,1,113,1001,905,84,5,2,4,0.0,0.06,0.06,2,0.12,0.58,0.23,6.57,58.20,52.62,4.88,0.29,0.12,0.23,1.28,4.83,1.40,3.49,0.06,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,3464,Midfielder,Serie B,A. Oliveri,Pescara,31,1754,2,25.0,3,0,38,34,15,28,9,127,594,491,34,87,3,23,0.0,0.00,0.10,2,0.10,1.28,0.15,6.52,30.48,25.19,1.74,4.46,0.15,1.18,1.95,1.74,0.77,1.44,0.46,0.0
126,3465,Midfielder,Serie B,A. Fiori,Frosinone,36,1831,5,58.0,19,2,17,10,6,8,21,110,578,488,22,46,5,30,0.0,0.10,0.25,7,0.34,2.85,0.93,5.41,28.41,23.99,1.08,2.26,0.25,1.47,0.84,0.49,0.29,0.39,1.03,0.0
127,3466,Midfielder,Serie B,A. Florenzi,Cosenza,30,2182,2,41.0,10,2,37,39,23,19,11,142,965,768,56,58,4,34,0.0,0.08,0.08,4,0.16,1.69,0.41,5.86,39.80,31.68,2.31,2.39,0.16,1.40,1.53,1.61,0.95,0.78,0.45,0.0
128,3467,Midfielder,Serie B,R. Floriani Mussolini,Cremonese,37,2890,2,16.0,8,1,44,92,21,43,1,119,529,351,68,92,5,18,0.0,0.03,0.06,3,0.09,0.50,0.25,3.71,16.47,10.93,2.12,2.87,0.16,0.56,1.37,2.87,0.65,1.34,0.03,0.0
129,3468,Midfielder,Serie B,J. Oyono,Frosinone,38,1585,0,6.0,3,1,36,49,6,21,0,105,596,484,54,43,1,18,0.0,0.06,0.00,1,0.06,0.34,0.17,5.96,33.84,27.48,3.07,2.44,0.06,1.02,2.04,2.78,0.34,1.19,0.00,0.0

In [21]:
#complete csv
finalData.to_csv("data/finalSCRAPEDdata/masterDatabases/SEBcomplete.csv")

# 2 Ablation Studies Datasets

In this section we will split the master dataframe into separate database files, to allow for future ablation studies to go smoothly.

here are the criteria for all variations:

- LALIGAcomplete90 = Any player that has played less than 90 minutes is removed from the dataset
- LALIGAcomplete25 = Any player that has less than 25% of the minutes from the .describe() function is removed

### 2.1 90 Minute Dataset Creation

Within this section we'll create the first dataset

In [22]:
#first lets save the 90minutes  dataframe as a separate one

finalData90 = finalData

In [23]:
#Next we will move onto data erasure within the given context of <90 minutes played
finalData90 = finalData90.drop(finalData90[finalData90["Mins"] < 90].index)

In [24]:
finalData90.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.00000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000
mean,3405.190083,30.644628,1445.603306,1.107438,17.677686,5.082645,1.338843,22.371901,41.016529,11.099174,28.752066,5.041322,79.074380,572.528926,454.892562,85.462810,29.165289,1.752066,13.033058,4.380165,0.080579,0.067107,2.446281,0.147603,1.20124,0.332727,4.991157,33.987686,26.820331,5.027603,1.886198,0.106281,0.869339,1.376777,2.399256,0.662314,1.810331,0.372975,0.297769
std,40.255706,8.458585,889.390629,1.395240,16.535928,5.547652,2.010612,18.889650,45.292932,11.119356,31.672354,5.473263,56.679386,447.020545,376.420682,129.057935,40.142319,2.161331,12.502622,17.926357,0.118267,0.091391,2.946609,0.172849,0.98788,0.352255,2.127000,12.764450,12.270466,4.821167,2.225877,0.130398,0.886713,0.896863,1.996147,0.588652,1.573198,0.417024,0.916600
min,3339.000000,4.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,26.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,10.680000,7.060000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3370.000000,27.000000,663.000000,0.000000,5.000000,1.000000,0.000000,7.000000,8.000000,2.000000,7.000000,1.000000,27.000000,190.000000,145.000000,19.000000,2.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.40000,0.060000,4.030000,24.720000,17.850000,1.980000,0.260000,0.000000,0.280000,0.810000,0.990000,0.230000,0.650000,0.040000,0.000000
50%,3403.000000,34.000000,1355.000000,1.000000,14.000000,3.000000,1.000000,19.000000,25.000000,8.000000,19.000000,3.000000,76.000000,451.000000,361.000000,47.000000,15.000000,1.000000,9.000000,0.000000,0.030000,0.040000,1.000000,0.080000,0.90000,0.210000,5.010000,31.510000,24.460000,3.890000,1.000000,0.070000,0.750000,1.300000,1.610000,0.640000,1.340000,0.220000,0.000000
75%,3441.000000,37.000000,2173.000000,2.000000,28.000000,8.000000,2.000000,36.000000,60.000000,18.000000,40.000000,8.000000,114.000000,827.000000,639.000000,103.000000,37.000000,3.000000,20.000000,0.000000,0.130000,0.100000,4.000000,0.230000,1.86000,0.520000,6.270000,40.250000,34.040000,5.810000,2.450000,0.160000,1.210000,1.920000,3.480000,0.950000,2.690000,0.550000,0.000000
max,3472.000000,40.000000,3598.000000,6.000000,67.000000,23.000000,13.000000,84.000000,210.000000,49.000000,169.000000,25.000000,275.000000,1888.000000,1698.000000,839.000000,226.000000,10.000000,55.000000,111.000000,0.600000,0.430000,16.000000,0.750000,3.87000,1.390000,10.160000,92.140000,77.140000,22.140000,11.250000,0.610000,7.860000,4.840000,9.280000,3.600000,7.980000,2.180000,4.110000

In [25]:
#Now that that has successfully gone through, we can create our next database

finalData90.to_csv("data/finalSCRAPEDdata/masterDatabases/SEBcomplete90.csv")

### 2.2 25% Minute Dataset Creation

Within this section we'll create the second dataset

In [26]:
#we'll do  the same as before, creating a separate dataframe

finalData25 = finalData

In [27]:
#first we need to find the threshold of minutes to remove
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.00000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000
mean,3406.000000,28.422222,1297.340741,0.992593,15.866667,4.562963,1.200000,20.066667,36.777778,9.955556,25.814815,4.518519,71.007407,513.570370,408.066667,76.614815,26.192593,1.570370,11.696296,3.925926,0.072222,0.060148,2.192593,0.132296,1.116296,0.31037,4.668148,32.427630,25.814519,4.544296,1.806444,0.095259,0.803407,1.260963,2.177407,0.612667,1.683852,0.334296,0.266889
std,39.115214,10.582629,948.600494,1.363141,16.536166,5.469873,1.946294,19.126523,44.649492,11.050675,31.203039,5.404326,58.688718,457.406699,382.077788,124.889861,38.989378,2.114417,12.472821,17.016949,0.114603,0.088890,2.887173,0.169692,1.000288,0.36621,2.536462,16.325479,15.192332,4.799187,2.371884,0.127612,0.903361,0.938070,2.009903,0.614443,1.615847,0.410812,0.872170
min,3339.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3372.500000,21.000000,478.000000,0.000000,2.000000,0.000000,0.000000,3.000000,5.000000,0.500000,4.000000,0.000000,17.000000,143.000000,107.500000,9.500000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.345000,0.00000,3.570000,23.490000,17.100000,1.485000,0.075000,0.000000,0.195000,0.415000,0.740000,0.025000,0.405000,0.000000,0.000000
50%,3406.000000,33.000000,1217.000000,0.000000,10.000000,2.000000,0.000000,16.000000,21.000000,6.000000,15.000000,3.000000,62.000000,432.000000,319.000000,36.000000,12.000000,1.000000,7.000000,0.000000,0.000000,0.000000,1.000000,0.070000,0.840000,0.17000,4.960000,30.290000,23.390000,3.510000,0.820000,0.060000,0.700000,1.260000,1.510000,0.590000,1.230000,0.180000,0.000000
75%,3439.500000,37.000000,2026.000000,2.000000,25.000000,8.000000,2.000000,33.500000,53.000000,16.000000,35.500000,7.000000,112.000000,780.500000,587.500000,95.500000,35.000000,2.000000,18.000000,0.000000,0.095000,0.080000,3.000000,0.205000,1.700000,0.48000,6.195000,39.955000,33.675000,5.665000,2.380000,0.150000,1.185000,1.890000,3.135000,0.870000,2.595000,0.505000,0.000000
max,3473.000000,40.000000,3598.000000,6.000000,67.000000,23.000000,13.000000,84.000000,210.000000,49.000000,169.000000,25.000000,275.000000,1888.000000,1698.000000,839.000000,226.000000,10.000000,55.000000,111.000000,0.600000,0.430000,16.000000,0.750000,3.870000,1.64000,11.450000,92.140000,90.000000,22.140000,12.860000,0.610000,7.860000,4.840000,9.280000,3.600000,7.980000,2.180000,4.110000

In [28]:
#We can see that the 25% cutoff is 478
finalData25 = finalData25.drop(finalData25[finalData25["Mins"] <= 478].index)

In [29]:
finalData25.describe()

,ID,App,Mins,Assists,Shots,shotsOnTarget,Goals,Tackles,Clearances,Interceptions,aerialsWon,Blocks,duelsWon,Passes,accuratePasses,longBalls,Crosses,bigChancesCreated,keyPasses,Saves,goalsPer90,assistsPer90,g+a,g+aPer90,shotsPer90,shotsOnTargetPer90,duelsWonPer90,passesPer90,accuratePassesPer90,longBallsPer90,crossesPer90,bigChancesCreatedPer90,keyPassesPer90,tacklesPer90,clearancesPer90,interceptionsPer90,aerialsWonPer90,blocksPer90,savesPer90
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.00000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000
mean,3406.871287,32.138614,1677.782178,1.297030,20.594059,5.990099,1.603960,26.099010,47.346535,12.831683,33.465347,5.782178,92.128713,665.396040,529.000000,98.841584,33.742574,2.049505,15.108911,5.000000,0.096535,0.074356,2.900990,0.170792,1.255347,0.37000,5.139307,33.831386,26.845743,4.600594,1.829802,0.113762,0.839010,1.436634,2.339109,0.636733,1.819406,0.356238,0.238317
std,40.928881,6.833783,785.178854,1.439059,16.570563,5.638253,2.102756,18.455625,46.834909,11.303158,32.602320,5.652617,52.913262,431.841802,368.752058,137.278165,42.310673,2.228794,12.615785,19.533561,0.123405,0.088965,3.018294,0.175440,1.014315,0.36063,2.060109,11.776930,11.464249,4.266118,1.978912,0.118210,0.596284,0.866246,1.864247,0.425114,1.465739,0.336535,0.826761
min,3339.000000,14.000000,483.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,64.000000,43.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.140000,10.680000,7.060000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3373.000000,29.000000,1067.000000,0.000000,7.000000,2.000000,0.000000,12.000000,10.000000,4.000000,11.000000,1.000000,52.000000,331.000000,247.000000,28.000000,3.000000,0.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.040000,0.470000,0.09000,4.100000,24.720000,18.900000,1.980000,0.320000,0.000000,0.300000,0.910000,0.990000,0.290000,0.690000,0.080000,0.000000
50%,3404.000000,35.000000,1548.000000,1.000000,16.000000,4.000000,1.000000,24.000000,35.000000,10.000000,23.000000,4.000000,88.000000,594.000000,453.000000,67.000000,20.000000,1.000000,11.000000,0.000000,0.060000,0.060000,2.000000,0.100000,0.900000,0.24000,5.140000,32.050000,24.700000,3.560000,1.000000,0.090000,0.780000,1.350000,1.730000,0.650000,1.350000,0.250000,0.000000
75%,3444.000000,37.000000,2341.000000,2.000000,30.000000,10.000000,2.000000,38.000000,65.000000,19.000000,42.000000,9.000000,129.000000,965.000000,745.000000,117.000000,46.000000,3.000000,23.000000,0.000000,0.150000,0.110000,4.000000,0.310000,2.140000,0.59000,6.510000,40.250000,34.040000,5.660000,2.440000,0.160000,1.210000,1.950000,3.470000,0.950000,2.800000,0.510000,0.000000
max,3472.000000,40.000000,3598.000000,6.000000,67.000000,23.000000,13.000000,84.000000,210.000000,49.000000,169.000000,25.000000,275.000000,1888.000000,1698.000000,839.000000,226.000000,10.000000,55.000000,111.000000,0.600000,0.430000,16.000000,0.750000,3.870000,1.39000,10.160000,71.990000,66.180000,21.410000,7.620000,0.610000,2.510000,4.840000,7.840000,1.690000,6.340000,1.350000,4.110000

In [30]:
#Now that the changes have successfully gone through, we'll save the final database
finalData25.to_csv("data/finalSCRAPEDdata/masterDatabases/SEBcomplete25.csv")